/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Caja;
import clases.Empleado;
import clases.Factura;
import clases.Hotel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitario.AdminFechas;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class GuiCaja extends javax.swing.JInternalFrame {

    private boolean efectivo = false;

    private Factura objFactura = new Factura();

    private Caja objCajaGuardado;
    private Factura objFactGuardado;

    /**
     * Creates new form GuiAreasDeTrabajo
     */
    public GuiCaja() {
        initComponents();
        this.actualizarElementosEnTabla();
        this.cbxEmpleado.setModel(PantallaPrincipal.gEmpleado.getComboboxModel());
        this.txtEfectivo.setVisible(false);
        this.txtTarjetatxt.setVisible(false);
        this.lblEfectivo.setVisible(false);
        this.lblTarjeta.setVisible(false);
        this.lblCambiio.setVisible(false);
        this.lblCambio.setVisible(false);

        this.btnCancelar.setEnabled(true);
        this.btnGuardar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtEfectivo = new javax.swing.JTextField();
        lblCostoTotal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProductos = new javax.swing.JTable();
        lblCambio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtbListaAreas3 = new javax.swing.JTable();
        cbxEmpleado = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        rbtnEfectivo = new javax.swing.JRadioButton();
        rbtnTarjeta = new javax.swing.JRadioButton();
        txtTarjetatxt = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lblEfectivo = new javax.swing.JLabel();
        lblTarjeta = new javax.swing.JLabel();
        lblCambiio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        txtBuscar1 = new javax.swing.JTextField();
        lblBuscar1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPrueba1 = new javax.swing.JTable();
        lblCambio1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        txtTotalPago1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnFactura1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTarjeta1 = new javax.swing.JTextField();
        txtEfectivo1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbListaAreas4 = new javax.swing.JTable();
        cbxEmpleado1 = new javax.swing.JComboBox<>();
        lbl2 = new javax.swing.JLabel();
        rbtnEfectivo1 = new javax.swing.JRadioButton();
        rbtnTarjeta1 = new javax.swing.JRadioButton();
        lbl3 = new javax.swing.JLabel();
        lblEfectivo1 = new javax.swing.JLabel();
        lblTarjeta1 = new javax.swing.JLabel();
        lblCambiio1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        txtEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        txtEfectivo.setText("Efectivo");
        txtEfectivo.setBorder(null);
        txtEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEfectivoMousePressed(evt);
            }
        });
        getContentPane().add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 40, 10));

        lblCostoTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblCostoTotal.setText("Costo total");
        getContentPane().add(lblCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 40, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 60, -1));

        tblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListaProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 520, 140));

        lblCambio.setForeground(new java.awt.Color(0, 0, 0));
        lblCambio.setText("Cambio");
        getContentPane().add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 10));

        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 40, 20));

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Total a pagar");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 90, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1900, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbListaAreas3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbListaAreas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListaAreas3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbListaAreas3MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(jtbListaAreas3);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 550, 220));

        cbxEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        cbxEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        cbxEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxEmpleadoMousePressed(evt);
            }
        });
        jPanel1.add(cbxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, -1));

        lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("Forma de pago");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 110, -1));

        buttonGroup1.add(rbtnEfectivo);
        rbtnEfectivo.setText("Efectivo");
        rbtnEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnEfectivoMousePressed(evt);
            }
        });
        jPanel1.add(rbtnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        buttonGroup1.add(rbtnTarjeta);
        rbtnTarjeta.setText("Tarjeta");
        rbtnTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnTarjetaMousePressed(evt);
            }
        });
        jPanel1.add(rbtnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, -1));

        txtTarjetatxt.setBackground(new java.awt.Color(255, 255, 255));
        txtTarjetatxt.setForeground(new java.awt.Color(0, 0, 0));
        txtTarjetatxt.setText("Codigo tarjeta");
        txtTarjetatxt.setBorder(null);
        txtTarjetatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTarjetatxtMousePressed(evt);
            }
        });
        jPanel1.add(txtTarjetatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 220, 30));

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Cajero");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));

        lblEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel1.add(lblEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, 30));

        lblTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel1.add(lblTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 260, 50));

        lblCambiio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel1.add(lblCambiio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar pago");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 110, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 60, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 60, 40));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cancelar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 450, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoTransparencia oscura.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 420, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFormulario.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 550, 460));

        jInternalFrame1.setBackground(new java.awt.Color(0, 0, 102));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        txtBuscar1.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar1.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar1.setBorder(null);
        txtBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscar1MousePressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 220, 30));

        lblBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(lblBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 260, 50));

        tblPrueba1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPrueba1);

        jInternalFrame1.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 530, 140));

        lblCambio1.setForeground(new java.awt.Color(0, 0, 0));
        lblCambio1.setText("Cambio");
        jInternalFrame1.getContentPane().add(lblCambio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 10));

        lblTotal1.setForeground(new java.awt.Color(0, 0, 0));
        jInternalFrame1.getContentPane().add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 40, 20));

        txtTotalPago1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(txtTotalPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Total a pagar");
        jInternalFrame1.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 80, -1));

        btnFactura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnFactura1.setBorder(null);
        btnFactura1.setBorderPainted(false);
        btnFactura1.setContentAreaFilled(false);
        btnFactura1.setFocusPainted(false);
        btnFactura1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnFactura1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnFactura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFactura1MousePressed(evt);
            }
        });
        btnFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactura1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 60, 40));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Imprimir factura");
        jInternalFrame1.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 90, -1));

        txtTarjeta1.setBackground(new java.awt.Color(255, 255, 255));
        txtTarjeta1.setForeground(new java.awt.Color(0, 0, 0));
        txtTarjeta1.setText("Codigo tarjeta");
        txtTarjeta1.setBorder(null);
        txtTarjeta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTarjeta1MousePressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 220, 30));

        txtEfectivo1.setBackground(new java.awt.Color(255, 255, 255));
        txtEfectivo1.setForeground(new java.awt.Color(0, 0, 0));
        txtEfectivo1.setText("Efectivo");
        txtEfectivo1.setBorder(null);
        txtEfectivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEfectivo1MousePressed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtEfectivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 40, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(1900, 720));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbListaAreas4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbListaAreas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListaAreas4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbListaAreas4MousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(jtbListaAreas4);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 550, 220));

        cbxEmpleado1.setBackground(new java.awt.Color(204, 204, 204));
        cbxEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        cbxEmpleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxEmpleado1MousePressed(evt);
            }
        });
        jPanel2.add(cbxEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 160, -1));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Forma de pago");
        jPanel2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, -1));

        buttonGroup1.add(rbtnEfectivo1);
        rbtnEfectivo1.setText("Efectivo");
        rbtnEfectivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnEfectivo1MousePressed(evt);
            }
        });
        jPanel2.add(rbtnEfectivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        buttonGroup1.add(rbtnTarjeta1);
        rbtnTarjeta1.setText("Tarjeta");
        rbtnTarjeta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnTarjeta1MousePressed(evt);
            }
        });
        jPanel2.add(rbtnTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 80, -1));

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Cajero");
        jPanel2.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, -1));

        lblEfectivo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblEfectivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, 30));

        lblTarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(lblTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 260, 50));

        lblCambiio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblCambiio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Confirmar pago");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, -1));

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar1.setBorder(null);
        btnGuardar1.setBorderPainted(false);
        btnGuardar1.setContentAreaFilled(false);
        btnGuardar1.setFocusPainted(false);
        btnGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 60, 40));

        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes1.setBorder(null);
        btnReportes1.setBorderPainted(false);
        btnReportes1.setContentAreaFilled(false);
        btnReportes1.setFocusPainted(false);
        btnReportes1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 60, 40));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Generar reporte");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, -1));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar1.setBorder(null);
        btnCancelar1.setBorderPainted(false);
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setFocusPainted(false);
        btnCancelar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 40));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Cancelar");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 50, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 450, -1));

        jInternalFrame1.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoTransparencia oscura.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 420, 100));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFormulario.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 550, 460));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbListaAreas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListaAreas3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbListaAreas3MouseClicked

    private void jtbListaAreas3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListaAreas3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbListaAreas3MousePressed

    private void cbxEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxEmpleadoMousePressed

    }//GEN-LAST:event_cbxEmpleadoMousePressed

    private void rbtnEfectivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnEfectivoMousePressed
        // TODO add your handling code here:
        efectivo = true;
        this.txtEfectivo.setVisible(true);
        this.txtTarjetatxt.setVisible(false);
        this.lblEfectivo.setVisible(true);
        this.lblTarjeta.setVisible(false);
        this.lblCambiio.setVisible(true);
        this.lblCambio.setVisible(true);

        this.btnCancelar.setEnabled(true);
        this.btnGuardar.setEnabled(true);

    }//GEN-LAST:event_rbtnEfectivoMousePressed

    private void rbtnTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTarjetaMousePressed
        // TODO add your handling code here:
        this.efectivo = false;
        this.txtEfectivo.setVisible(false);
        this.txtTarjetatxt.setVisible(true);
        this.lblEfectivo.setVisible(false);
        this.lblTarjeta.setVisible(true);
        this.lblCambiio.setVisible(false);
        this.lblCambio.setVisible(false);

        this.btnCancelar.setEnabled(true);
        this.btnGuardar.setEnabled(true);
    }//GEN-LAST:event_rbtnTarjetaMousePressed

    private void txtEfectivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEfectivoMousePressed
        // TODO add your handling code here:
        this.txtEfectivo.setText("");
    }//GEN-LAST:event_txtEfectivoMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        /**
         * private Empleado cajero; private ListaProductos lista; private String
         * formaPago; private float efectivo; private float cambio; private
         * float totalPago;
         */
        try {
            Empleado objEmpleado;
            String formaPago;
            float cambio = 0;
            float montoEfectivo;
            float totalPago;

            totalPago = (float) PantallaPrincipal.gLstProductos.total();

            int indexEmpleado = this.cbxEmpleado.getSelectedIndex();
            objEmpleado = PantallaPrincipal.gEmpleado.getObjetoEmpleado(indexEmpleado);
            if (this.efectivo) {
                formaPago = "Efectivo";
                montoEfectivo = Float.parseFloat(this.txtEfectivo.getText());
                if (montoEfectivo < totalPago) {
                    JOptionPane.showMessageDialog(null, "Efectivo insuficiente");
                } else {
                    cambio = montoEfectivo - totalPago;
                    this.lblCambio.setText(Float.toString(cambio));
                    Caja objCaja = new Caja();
                    objCaja.setCajero(objEmpleado);
                    objCaja.setCambio(cambio);
                    objCaja.setEfectivo(montoEfectivo);
                    objCaja.setFormaPago(formaPago);
                    objCaja.setTotalPago(totalPago);
                    objCaja.setRsv(null);

                    if (JOptionPane.showConfirmDialog(this, "Confirmar pago", "Confirmar pago realizado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        PantallaPrincipal.gCaja.agregarCaja(objCaja);

                        this.actualizarElementosEnTabla();
                        JOptionPane.showMessageDialog(null, "Operasion realizada con exito");
                    }

                    //Imprimir factura
                    if (JOptionPane.showConfirmDialog(this, "¿Desea imprimir factura?", "Imprimir factura", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                        Caja objCajero;
                        Date fecha;
                        objCajero = PantallaPrincipal.gCaja.getObjCaja(0);
                        Hotel htl = PantallaPrincipal.gHtl.objHotel(0);
                        fecha = AdminFechas.getFechaActual();
                        Factura objFactura = new Factura();
                        objFactura.setCajero(objCajero);
                        objFactura.setFechaPAgo(fecha);
                        objFactura.setHotel(htl);

                        PantallaPrincipal.gFact.agregarFactura(objFactura);
                        int tamanioFacturas = PantallaPrincipal.gFact.lstFactura.size();
                        String nombreArchivo = "Fact-"+tamanioFacturas;
                        String contenido = PantallaPrincipal.gFact.generarFactura();
                        String ruta = "Factura/" + nombreArchivo;

                        try {
                            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
                            Document doc = new Document();
                            PdfWriter.getInstance(doc, archivo);
                            doc.open();
                            doc.add(new Paragraph(contenido));
                            doc.close();
                            JOptionPane.showMessageDialog(null, "Factura generada con exito");
                        } catch (Exception e) {
                            System.out.println("error" + e);
                        }

                        JOptionPane.showMessageDialog(null, "Operasion realizada con exito");
                    }

                }

            } else {
                formaPago = "Tarjeta";
                cambio = 0;
                montoEfectivo = 0;
                Caja objCaja = new Caja();
                objCaja.setCajero(objEmpleado);
                objCaja.setCambio(cambio);
                objCaja.setEfectivo(montoEfectivo);
                objCaja.setFormaPago(formaPago);
                objCaja.setTotalPago(totalPago);
                objCaja.setRsv(null);

                if (JOptionPane.showConfirmDialog(this, "Confirmar pago", "Confirmar pago realizado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    PantallaPrincipal.gCaja.agregarCaja(objCaja);
                    
                    

                    this.actualizarElementosEnTabla();
                    JOptionPane.showMessageDialog(null, "Operasion realizada con exito");
                }
                
                if (JOptionPane.showConfirmDialog(this, "¿Desea imprimir factura?", "Imprimir factura", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                        Caja objCajero;
                        Date fecha;
                        int posicionCaja = PantallaPrincipal.gCaja.lstCaja.size()-1;
                        objCajero = PantallaPrincipal.gCaja.getObjCaja(posicionCaja);
                        Hotel htl = PantallaPrincipal.gHtl.objHotel(0);
                        fecha = AdminFechas.getFechaActual();
                        Factura objFactura = new Factura();
                        objFactura.setCajero(objCajero);
                        objFactura.setFechaPAgo(fecha);
                        objFactura.setHotel(htl);

                        PantallaPrincipal.gFact.agregarFactura(objFactura);
                        
                        int tamanioFacturas = PantallaPrincipal.gFact.lstFactura.size();
                        String nombreArchivo = "Fact-"+tamanioFacturas;
                        String contenido = PantallaPrincipal.gFact.generarFactura();
                        String ruta = "Factura/" + nombreArchivo;

                        try {
                            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
                            Document doc = new Document();
                            PdfWriter.getInstance(doc, archivo);
                            doc.open();
                            doc.add(new Paragraph(contenido));
                            doc.close();
                            JOptionPane.showMessageDialog(null, "Factura generada con exito");
                        } catch (Exception e) {
                            System.out.println("error" + e);
                        }

                        JOptionPane.showMessageDialog(null, "Operasion realizada con exito");
                    }
                

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.btnCancelar.setEnabled(false);
        this.btnGuardar.setEnabled(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar1MousePressed

    private void btnFactura1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFactura1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFactura1MousePressed

    private void btnFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFactura1ActionPerformed

    private void txtTarjeta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjeta1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjeta1MousePressed

    private void txtEfectivo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEfectivo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivo1MousePressed

    private void jtbListaAreas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListaAreas4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbListaAreas4MouseClicked

    private void jtbListaAreas4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListaAreas4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbListaAreas4MousePressed

    private void cbxEmpleado1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxEmpleado1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEmpleado1MousePressed

    private void rbtnEfectivo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnEfectivo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEfectivo1MousePressed

    private void rbtnTarjeta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTarjeta1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTarjeta1MousePressed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void tblListaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProductosMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblListaProductosMousePressed

    private void txtTarjetatxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjetatxtMousePressed
        // TODO add your handling code here:
        this.txtTarjetatxt.setText("");
    }//GEN-LAST:event_txtTarjetatxtMousePressed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID producto", "Nombre del producto", "Cantidad", "Costo unitario", "Costo total"};
        DefaultTableModel tablaListaProductos = new DefaultTableModel(PantallaPrincipal.gLstProductos.getArrayGestion(), tituloColumnas);

        this.tblListaProductos.setModel(tablaListaProductos);

        this.lblCostoTotal.setText(Double.toString(PantallaPrincipal.gLstProductos.total()));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnFactura1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnReportes1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxEmpleado;
    private javax.swing.JComboBox<String> cbxEmpleado1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jtbListaAreas3;
    private javax.swing.JTable jtbListaAreas4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblBuscar1;
    private javax.swing.JLabel lblCambiio;
    private javax.swing.JLabel lblCambiio1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCambio1;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblEfectivo;
    private javax.swing.JLabel lblEfectivo1;
    private javax.swing.JLabel lblTarjeta;
    private javax.swing.JLabel lblTarjeta1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JRadioButton rbtnEfectivo;
    private javax.swing.JRadioButton rbtnEfectivo1;
    private javax.swing.JRadioButton rbtnTarjeta;
    private javax.swing.JRadioButton rbtnTarjeta1;
    private javax.swing.JTable tblListaProductos;
    private javax.swing.JTable tblPrueba1;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtEfectivo1;
    private javax.swing.JTextField txtTarjeta1;
    private javax.swing.JTextField txtTarjetatxt;
    private javax.swing.JLabel txtTotalPago1;
    // End of variables declaration//GEN-END:variables
}
