/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.AreaDeTrabajo;
import clases.Empleado;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitario.AdminFechas;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class GuiEmpleados extends javax.swing.JInternalFrame {

    private boolean agregando = false;
    private int posicionElemento;
    private int id;

    /**
     * Creates new form GuiCategoriaHabitacion
     */
    public GuiEmpleados() {

        initComponents();
        this.cbxAreaDeTrabajo.setModel(PantallaPrincipal.gArea.getComboboxModel());
        this.actualizarElementosEnTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupEstadoCivil = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        cbxFecaNacimiento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxMesNacimiento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtAnioNacimiento = new javax.swing.JTextField();
        lblImagenID4 = new javax.swing.JLabel();
        txtNumTelefono = new javax.swing.JTextField();
        fontoTexto5 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        fontoTexto4 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        fontoTexto2 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        fontoTexto = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblNuevo = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEditar1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        lblCategoria7 = new javax.swing.JLabel();
        lblCorreo2 = new javax.swing.JLabel();
        lblCorreo3 = new javax.swing.JLabel();
        lblCorreo4 = new javax.swing.JLabel();
        txtNumIdentidad = new javax.swing.JTextField();
        fontoTexto8 = new javax.swing.JLabel();
        lblCorreo5 = new javax.swing.JLabel();
        lblCorreo6 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblImagenID3 = new javax.swing.JLabel();
        cbxAreaDeTrabajo = new javax.swing.JComboBox<>();
        txtSueldo = new javax.swing.JTextField();
        lblImagenID1 = new javax.swing.JLabel();
        lblCorreo7 = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        lblImagenID2 = new javax.swing.JLabel();
        jradViudo = new javax.swing.JRadioButton();
        jradSoltero = new javax.swing.JRadioButton();
        jradCasado = new javax.swing.JRadioButton();
        cbxFechaInicio = new javax.swing.JComboBox<>();
        cbxMesInicio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        lblCancelar1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblEmpleado = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        fontoTexto9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario Empleados ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(670, 730));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxFecaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        cbxFecaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        cbxFecaNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(cbxFecaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 20));

        jLabel5.setText("Dia");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 30, 20));

        jLabel6.setText("Mes");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 30, -1));

        cbxMesNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        cbxMesNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cbxMesNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 80, 20));

        jLabel7.setText("Año");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 30, -1));

        txtAnioNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txtAnioNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtAnioNacimiento.setText("000");
        txtAnioNacimiento.setBorder(null);
        txtAnioNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAnioNacimientoMousePressed(evt);
            }
        });
        txtAnioNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioNacimientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnioNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 285, 40, 10));

        lblImagenID4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 60, 20));

        txtNumTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtNumTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtNumTelefono.setText("número de teléfono");
        txtNumTelefono.setBorder(null);
        txtNumTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumTelefonoMouseClicked(evt);
            }
        });
        txtNumTelefono.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNumTelefonoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, 30));

        fontoTexto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, 50));

        lblCorreo1.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo1.setText("Número de teléfono");
        jPanel2.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 20));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo Electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtCorreoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 30));

        fontoTexto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 50));

        lblCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo.setText("Correo electronico");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Datos personales del empleado");
        jPanel2.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerApellido.setText("Primer apellido");
        txtPrimerApellido.setBorder(null);
        txtPrimerApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerApellidoMouseClicked(evt);
            }
        });
        txtPrimerApellido.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtPrimerApellidoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 220, 30));

        fontoTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 50));

        txtPrimerNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerNombre.setText("Primer nombre");
        txtPrimerNombre.setBorder(null);
        txtPrimerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMousePressed(evt);
            }
        });
        txtPrimerNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtPrimerNombreCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        fontoTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 50));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 1 nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 2 nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 60, 40));

        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Nuevo");
        jPanel2.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setText("Cancelar");
        jPanel2.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 60, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 60, 40));

        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setText("Guardar");
        jPanel2.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 1.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 50, 40));

        lblEditar1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar1.setText("Eliminar");
        jPanel2.add(lblEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 40, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 2.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setEnabled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 3.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 1.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 60, 40));

        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");
        jPanel2.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 40, 10));

        lblCategoria4.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria4.setForeground(new java.awt.Color(0, 153, 153));
        lblCategoria4.setText("Primer nombre");
        jPanel2.add(lblCategoria4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblCategoria7.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria7.setForeground(new java.awt.Color(0, 153, 153));
        lblCategoria7.setText("Primer apellido");
        jPanel2.add(lblCategoria7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 20));

        lblCorreo2.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo2.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo2.setText("Fecha de nacimiento");
        jPanel2.add(lblCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        lblCorreo3.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo3.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo3.setText("Estsdo civil");
        jPanel2.add(lblCorreo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, 20));

        lblCorreo4.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo4.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo4.setText("Fecha de inicio laboral");
        jPanel2.add(lblCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, 20));

        txtNumIdentidad.setBackground(new java.awt.Color(255, 255, 255));
        txtNumIdentidad.setForeground(new java.awt.Color(0, 0, 0));
        txtNumIdentidad.setText("Numero de tarjeta de identidad");
        txtNumIdentidad.setBorder(null);
        txtNumIdentidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumIdentidadMouseClicked(evt);
            }
        });
        txtNumIdentidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNumIdentidadCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNumIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIdentidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 220, 30));

        fontoTexto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 250, 50));

        lblCorreo5.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo5.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo5.setText("Numero de identidad");
        jPanel2.add(lblCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        lblCorreo6.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo6.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo6.setText("Área de trabajo");
        jPanel2.add(lblCorreo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 20));

        txtAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtAnio.setForeground(new java.awt.Color(0, 0, 0));
        txtAnio.setText("000");
        txtAnio.setBorder(null);
        txtAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAnioMousePressed(evt);
            }
        });
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 385, 40, 10));

        lblImagenID3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 60, 20));

        cbxAreaDeTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        cbxAreaDeTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(cbxAreaDeTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 20));

        txtSueldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSueldo.setForeground(new java.awt.Color(0, 0, 0));
        txtSueldo.setText("000");
        txtSueldo.setBorder(null);
        txtSueldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSueldoMousePressed(evt);
            }
        });
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 40, 10));

        lblImagenID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 60, 50));

        lblCorreo7.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo7.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo7.setText("Sueldo");
        jPanel2.add(lblCorreo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 50, 20));

        lblID1.setBackground(new java.awt.Color(255, 255, 255));
        lblID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(255, 255, 255));
        lblID1.setText("ID empleado");
        jPanel2.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 20));

        txtID2.setBackground(new java.awt.Color(255, 255, 255));
        txtID2.setForeground(new java.awt.Color(0, 0, 0));
        txtID2.setText("000");
        txtID2.setBorder(null);
        txtID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 10));

        lblImagenID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 60, 70));

        btnGrupEstadoCivil.add(jradViudo);
        jradViudo.setText("Viudo");
        jPanel2.add(jradViudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 60, -1));

        btnGrupEstadoCivil.add(jradSoltero);
        jradSoltero.setText("Soltero");
        jPanel2.add(jradSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        btnGrupEstadoCivil.add(jradCasado);
        jradCasado.setText("Casado");
        jPanel2.add(jradCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        cbxFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        cbxFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        cbxFechaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(cbxFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 50, 20));

        cbxMesInicio.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesInicio.setForeground(new java.awt.Color(0, 0, 0));
        cbxMesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cbxMesInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 80, 20));

        jLabel3.setText("Dia");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 30, 20));

        jLabel2.setText("Año");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 30, -1));

        jLabel4.setText("Mes");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 30, -1));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 60, 40));

        lblCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar1.setText("Reporte");
        jPanel2.add(lblCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 540, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 450, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de empleados registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEmpleadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblEmpleadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtblEmpleado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 580, 220));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 3.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 2.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 50));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setText("Buscar por ID");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 20));

        fontoTexto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel1.add(fontoTexto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 370, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 600, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.posicionElemento = PantallaPrincipal.gEmpleado.buscarPorIdentificacion(this.txtBuscar.getText());
        if (posicionElemento == -1) {
            JOptionPane.showConfirmDialog(null, "No se encontro resultado con los parametros de busqueda");
        } else {
            Empleado objEmpleado = PantallaPrincipal.gEmpleado.getObjetoEmpleado(this.posicionElemento);
            this.txtCorreo.setText(objEmpleado.getCorreo());
            this.cbxFechaInicio.setEditable(false);

            //this.cbxFechaInicio.setSelectedIndex(WIDTH);
            // this.txtFechaNacimiento.setText(objEmpleado.getFechaNacimiento().toString());
            this.txtID2.setText(Integer.toString(objEmpleado.getIdEmpleado()));
            this.txtNumIdentidad.setText(objEmpleado.getNumIden());
            this.txtNumTelefono.setText(objEmpleado.getNumTelefono());
            this.txtPrimerApellido.setText(objEmpleado.getpApellido());
            this.txtPrimerNombre.setText(objEmpleado.getpNombre());
            this.txtSueldo.setText(Double.toString(objEmpleado.getSueldo()));

            this.btnEditar.setEnabled(true);
            this.btnEliminar.setEnabled(true);
            this.btnGuardar.setEnabled(false);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.agregando = true;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnCancelar.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * Metodo que retorna el estado civil
     *
     * @return Estado civil.
     */
    public String estadoCivil() {
        String estCivil = null;
        if (this.jradCasado.isSelected()) {
            estCivil = "Casado";
        } else {
            if (this.jradSoltero.isSelected()) {
                estCivil = "Soltero";
            } else {
                if (this.jradViudo.isSelected()) {
                    estCivil = "Viudo";
                }
            }
        }
        return estCivil;
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // TODO add your handling code here:
        try {
            if (agregando) {
                int id = PantallaPrincipal.gEmpleado.AsignarId();
                String nombre, apellido, correo, telefono, estadoCivil, numIdentidad;
                Date fechaNacimmiento;
                Date fechaInicioLab;

                String area;
                AreaDeTrabajo areaTrabajo;
                double sueldo;
                String dia, mes, anio;

                nombre = this.txtPrimerNombre.getText();
                apellido = this.txtPrimerApellido.getText();
                correo = this.txtCorreo.getText();
                telefono = this.txtNumTelefono.getText();

                dia = Integer.toString(cbxFecaNacimiento.getSelectedIndex() + 1);
                mes = Integer.toString(cbxMesNacimiento.getSelectedIndex());
                anio = txtAnioNacimiento.getText();

                fechaNacimmiento = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);

                estadoCivil = this.estadoCivil();
                numIdentidad = this.txtNumIdentidad.getText();

                dia = Integer.toString(cbxFechaInicio.getSelectedIndex() + 1);
                mes = Integer.toString(cbxMesInicio.getSelectedIndex());
                anio = txtAnio.getText();

                fechaInicioLab = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);
                //Obtener el objeto Area de trabajo
                int index = this.cbxAreaDeTrabajo.getSelectedIndex();
                areaTrabajo = PantallaPrincipal.gArea.getObj(index);

                //Asignar el area al empleado
                area = areaTrabajo.getDescripcionarea();

                sueldo = Double.parseDouble(this.txtSueldo.getText());

                //crear el objeto
                Empleado objEmpleado = new Empleado();
                objEmpleado.setpNombre(nombre);
                objEmpleado.setpApellido(apellido);
                objEmpleado.setSueldo(sueldo);
                objEmpleado.setNumTelefono(telefono);
                objEmpleado.setNumIden(numIdentidad);
                objEmpleado.setIdEmpleado(id);
                objEmpleado.setFechaNacimiento(fechaNacimmiento);
                objEmpleado.setFechaInicioLaboral(fechaInicioLab);
                objEmpleado.setEstadoCivil(estadoCivil);
                objEmpleado.setCorreo(correo);
                objEmpleado.setArea(areaTrabajo);

                //Agregar el objeto a la gestion
                PantallaPrincipal.gEmpleado.agregarEmpleado(objEmpleado);

                actualizarElementosEnTabla();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnCancelar.setEnabled(false);
                agregando = false;
            } else {
                int id = PantallaPrincipal.gEmpleado.AsignarId();
                String nombre, apellido, correo, telefono, estadoCivil, numIdentidad;
                Date fechaNacimmiento;
                Date fechaInicioLab;

                String area;
                AreaDeTrabajo areaTrabajo;
                double sueldo;

                nombre = this.txtPrimerNombre.getText();
                apellido = this.txtPrimerApellido.getText();
                correo = this.txtCorreo.getText();
                telefono = this.txtNumTelefono.getText();
                String dia, mes, anio;

                dia = Integer.toString(cbxFecaNacimiento.getSelectedIndex() + 1);
                mes = Integer.toString(cbxMesNacimiento.getSelectedIndex());
                anio = txtAnioNacimiento.getText();

                fechaNacimmiento = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);

                estadoCivil = this.estadoCivil();
                numIdentidad = this.txtNumIdentidad.getText();

                dia = Integer.toString(cbxFechaInicio.getSelectedIndex() + 1);
                mes = Integer.toString(cbxMesInicio.getSelectedIndex());
                anio = txtAnio.getText();
                fechaInicioLab = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);
                //Obtener el objeto Area de trabajo
                int index = this.cbxAreaDeTrabajo.getSelectedIndex();
                areaTrabajo = PantallaPrincipal.gArea.getObj(index);

                //Asignar el area al empleado
                area = areaTrabajo.getDescripcionarea();

                sueldo = Double.parseDouble(this.txtSueldo.getText());

                //crear el objeto
                Empleado objEditado = new Empleado();
                objEditado.setpNombre(nombre);
                objEditado.setpApellido(apellido);
                objEditado.setSueldo(sueldo);
                objEditado.setNumTelefono(telefono);
                objEditado.setNumIden(numIdentidad);
                objEditado.setIdEmpleado(id);
                objEditado.setFechaNacimiento(fechaNacimmiento);
                objEditado.setFechaInicioLaboral(fechaInicioLab);
                objEditado.setEstadoCivil(estadoCivil);
                objEditado.setCorreo(correo);
                objEditado.setArea(areaTrabajo);

                //Agregar el objeto a la gestion
                PantallaPrincipal.gEmpleado.modificarEmpleado(posicionElemento, objEditado);

                actualizarElementosEnTabla();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnCancelar.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al registra"+ e);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.agregando = false;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        id = Integer.parseInt(this.txtID2.getText());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            PantallaPrincipal.gEmpleado.eliminarEmpleado(posicionElemento);
            this.actualizarElementosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed

    private void txtPrimerNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMouseClicked
        // TODO add your handling code here:
        this.txtPrimerNombre.setText("");
    }//GEN-LAST:event_txtPrimerNombreMouseClicked

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        // TODO add your handling code here:
        this.txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtPrimerNombreCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPrimerNombreCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreCaretPositionChanged

    private void jtblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblEmpleadoMouseClicked

    private void jtblEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEmpleadoMousePressed
        // TODO add your handling code here:
        this.posicionElemento = this.jtblEmpleado.getSelectedRow();
        Empleado objEmpleado = PantallaPrincipal.gEmpleado.getObjetoEmpleado(this.posicionElemento);
        this.txtCorreo.setText(objEmpleado.getCorreo());
        this.cbxFechaInicio.setEditable(false);

        //this.cbxFechaInicio.setSelectedIndex(WIDTH);
        // this.txtFechaNacimiento.setText(objEmpleado.getFechaNacimiento().toString());
        this.txtID2.setText(Integer.toString(objEmpleado.getIdEmpleado()));
        this.txtNumIdentidad.setText(objEmpleado.getNumIden());
        this.txtNumTelefono.setText(objEmpleado.getNumTelefono());
        this.txtPrimerApellido.setText(objEmpleado.getpApellido());
        this.txtPrimerNombre.setText(objEmpleado.getpNombre());
        this.txtSueldo.setText(Double.toString(objEmpleado.getSueldo()));

        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnGuardar.setEnabled(false);


    }//GEN-LAST:event_jtblEmpleadoMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        this.txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed

    }//GEN-LAST:event_btnBuscarMousePressed

    private void txtPrimerApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerApellidoMouseClicked
        // TODO add your handling code here:
        this.txtPrimerApellido.setText("");
    }//GEN-LAST:event_txtPrimerApellidoMouseClicked

    private void txtPrimerApellidoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPrimerApellidoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoCaretPositionChanged

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCorreoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoCaretPositionChanged

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNumTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumTelefonoMouseClicked
        // TODO add your handling code here:
        this.txtNumTelefono.setText("");
    }//GEN-LAST:event_txtNumTelefonoMouseClicked

    private void txtNumTelefonoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNumTelefonoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTelefonoCaretPositionChanged

    private void txtNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTelefonoActionPerformed

    private void txtNumIdentidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumIdentidadMouseClicked
        // TODO add your handling code here:
        this.txtNumIdentidad.setText("");
    }//GEN-LAST:event_txtNumIdentidadMouseClicked

    private void txtNumIdentidadCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNumIdentidadCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdentidadCaretPositionChanged

    private void txtNumIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdentidadActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSueldoActionPerformed

    private void txtID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID2ActionPerformed

    private void txtPrimerNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPrimerNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        this.txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtSueldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSueldoMousePressed
        // TODO add your handling code here:
        this.txtSueldo.setText("");
    }//GEN-LAST:event_txtSueldoMousePressed

    private void txtAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMousePressed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtAnioNacimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioNacimientoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioNacimientoMousePressed

    private void txtAnioNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioNacimientoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

        String nombreArchivo = "Empleados";
        String contenido = PantallaPrincipal.gEmpleado.getInformacionGestion();
        String ruta = "Reportes/" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }

    }//GEN-LAST:event_btnReportesActionPerformed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID", "Nombre", "Apellido", "Correo electronico", "Num. telefono", "Num. identidad", "Area de trabajo", "Sueldo"};
        DefaultTableModel tablaEmpleado = new DefaultTableModel(PantallaPrincipal.gEmpleado.getArrayGestion(), tituloColumnas);

        this.jtblEmpleado.setModel(tablaEmpleado);
        AdminSerializacion.guardar(PantallaPrincipal.gEmpleado, "objEmpleado.obj");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrupEstadoCivil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cbxAreaDeTrabajo;
    private javax.swing.JComboBox<String> cbxFecaNacimiento;
    private javax.swing.JComboBox<String> cbxFechaInicio;
    private javax.swing.JComboBox<String> cbxMesInicio;
    private javax.swing.JComboBox<String> cbxMesNacimiento;
    private javax.swing.JLabel fontoTexto;
    private javax.swing.JLabel fontoTexto2;
    private javax.swing.JLabel fontoTexto4;
    private javax.swing.JLabel fontoTexto5;
    private javax.swing.JLabel fontoTexto8;
    private javax.swing.JLabel fontoTexto9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jradCasado;
    private javax.swing.JRadioButton jradSoltero;
    private javax.swing.JRadioButton jradViudo;
    private javax.swing.JTable jtblEmpleado;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCancelar1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria7;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo2;
    private javax.swing.JLabel lblCorreo3;
    private javax.swing.JLabel lblCorreo4;
    private javax.swing.JLabel lblCorreo5;
    private javax.swing.JLabel lblCorreo6;
    private javax.swing.JLabel lblCorreo7;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEditar1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblImagenID1;
    private javax.swing.JLabel lblImagenID2;
    private javax.swing.JLabel lblImagenID3;
    private javax.swing.JLabel lblImagenID4;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnioNacimiento;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtNumIdentidad;
    private javax.swing.JTextField txtNumTelefono;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
