/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.CategoriaHabitacion;
import clases.Habitacion;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class GuiHabitacion extends javax.swing.JInternalFrame {

    private boolean agregando;
    private int posicionElemento;

    /**
     * Creates new form GuiCategoriaHabitacion
     */
    public GuiHabitacion() {

        initComponents();
        this.txtDisponibilidad.setEnabled(false);
        this.txtNumPiso.setEnabled(false);
        this.txtNumeroHabitacion.setEnabled(false);

        this.btnGuardar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(false);

        this.txtCapacidad.setEnabled(false);
        this.txtDescripcion.setEnabled(false);
        this.txtID.setEnabled(false);
        this.txtPrecioDia.setEnabled(false);
        this.actualizarElementosEnTabla();
        this.cbxCategoria.setModel(PantallaPrincipal.gCatHab.getComboboxModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblPrecio1 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        lblImagenID4 = new javax.swing.JLabel();
        lblNumeroHabitacion1 = new javax.swing.JLabel();
        txtNumPiso = new javax.swing.JTextField();
        lblImagenID3 = new javax.swing.JLabel();
        lblNumeroHabitacion = new javax.swing.JLabel();
        txtNumeroHabitacion = new javax.swing.JTextField();
        lblImagenID2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblImagenID = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        lblCategoria2 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioDia = new javax.swing.JTextField();
        lblImagenID1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblNuevo = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEditar1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblID1 = new javax.swing.JLabel();
        txtDisponibilidad = new javax.swing.JTextField();
        lblImagenID5 = new javax.swing.JLabel();
        btnReportes3 = new javax.swing.JButton();
        lblCancelar1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblHabitacion = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        cbxBuscar = new javax.swing.JComboBox<>();
        txtBuscarHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario de Habitación ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio1.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio1.setText("Capacidad");
        jPanel2.add(lblPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        txtCapacidad.setEditable(false);
        txtCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setForeground(new java.awt.Color(0, 0, 0));
        txtCapacidad.setText("000");
        txtCapacidad.setBorder(null);
        txtCapacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCapacidadMouseClicked(evt);
            }
        });
        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 10));

        lblImagenID4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, 30));

        lblNumeroHabitacion1.setBackground(new java.awt.Color(255, 255, 255));
        lblNumeroHabitacion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroHabitacion1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroHabitacion1.setText("Número de piso");
        jPanel2.add(lblNumeroHabitacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        txtNumPiso.setBackground(new java.awt.Color(255, 255, 255));
        txtNumPiso.setForeground(new java.awt.Color(0, 0, 0));
        txtNumPiso.setText("000");
        txtNumPiso.setBorder(null);
        txtNumPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPisoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 40, 10));

        lblImagenID3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 60, 30));

        lblNumeroHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        lblNumeroHabitacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroHabitacion.setText("Número de habitación");
        jPanel2.add(lblNumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtNumeroHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroHabitacion.setText("000");
        txtNumeroHabitacion.setBorder(null);
        txtNumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroHabitacionActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 40, 10));

        lblImagenID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 30));

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setText("000");
        txtID.setBorder(null);
        txtID.setEnabled(false);
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 55, 40, 10));

        lblImagenID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 60));

        lblCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setText("Categoría");
        jPanel2.add(lblCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        lblCategoria2.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria2.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setText("Descripción");
        jPanel2.add(lblCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 30));

        cbxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cbxCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría", " " }));
        cbxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCategoriaItemStateChanged(evt);
            }
        });
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Precio por dia");
        jPanel2.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 20));

        txtPrecioDia.setEditable(false);
        txtPrecioDia.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioDia.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioDia.setText("0.00");
        txtPrecioDia.setBorder(null);
        txtPrecioDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioDiaMouseClicked(evt);
            }
        });
        txtPrecioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioDiaActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecioDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 40, 10));

        lblImagenID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 60, 30));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 1 nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 2 nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 60, 40));

        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Nuevo");
        jPanel2.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setText("Cancelar");
        jPanel2.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 60, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 60, 40));

        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setText("Guardar");
        jPanel2.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 1.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 70, 40));

        lblEditar1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar1.setText("Eliminar");
        jPanel2.add(lblEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 50, 20));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 2.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setEnabled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 3.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 1.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 70, 40));

        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");
        jPanel2.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 50, 20));

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        lblID1.setBackground(new java.awt.Color(255, 255, 255));
        lblID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(255, 255, 255));
        lblID1.setText("Disponibilidad");
        jPanel2.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        txtDisponibilidad.setBackground(new java.awt.Color(255, 255, 255));
        txtDisponibilidad.setForeground(new java.awt.Color(0, 0, 0));
        txtDisponibilidad.setText("Disponible");
        txtDisponibilidad.setBorder(null);
        txtDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisponibilidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 40, 10));

        lblImagenID5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 60, 30));

        btnReportes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes3.setBorder(null);
        btnReportes3.setBorderPainted(false);
        btnReportes3.setContentAreaFilled(false);
        btnReportes3.setFocusPainted(false);
        btnReportes3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 60, 40));

        lblCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar1.setText("Reporte");
        jPanel2.add(lblCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 40, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 450, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de habitaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblHabitacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtblHabitacionMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtblHabitacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 550, 210));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 3.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 2.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, 50));

        cbxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por ID", "Buscar por numero de habitacion", " " }));
        cbxBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBuscarItemStateChanged(evt);
            }
        });
        cbxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(cbxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        txtBuscarHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarHabitacion.setText("Buscar habitacion");
        txtBuscarHabitacion.setBorder(null);
        txtBuscarHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarHabitacionMouseClicked(evt);
            }
        });
        txtBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 380, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFormulario.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 620, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 590, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Habitacion objHabitacion;
        int posicion;
        String accion = this.cbxBuscar.getSelectedItem().toString();

        try {
            if (accion.equalsIgnoreCase("Buscar por ID")) {
                //Buscar el objeto
                posicion = PantallaPrincipal.gHab.buscarPorId(Integer.parseInt(this.txtBuscarHabitacion.getText()));
                if (posicion == -1) {
                    JOptionPane.showMessageDialog(null, "No se encontro ningun resultado con el ID ingresado");
                } else {
                    // TODO add your handling code here:
                    objHabitacion = PantallaPrincipal.gHab.getObjHabitacion(posicion);

                    this.txtID.setText(Integer.toString(objHabitacion.getIdHabitacion()));
                    this.txtNumeroHabitacion.setText(Integer.toString(objHabitacion.getNumHabitacion()));
                    this.txtNumPiso.setText(Integer.toString(objHabitacion.getNumPiso()));
                    this.txtCapacidad.setText(Integer.toString(objHabitacion.getCapacidad()));
                    this.txtPrecioDia.setText(Double.toString(objHabitacion.getPrecio()));
                    this.txtDisponibilidad.setText(objHabitacion.getDescripcion());
                    this.txtDescripcion.setText(objHabitacion.getDescripcion());

                    this.btnEditar.setEnabled(true);
                    this.btnEliminar.setEnabled(true);
                }

            } else {
                if (accion.equalsIgnoreCase("Buscar por numero de habitacion")) {
                    posicion = PantallaPrincipal.gHab.buscarPorNumeroHabitacion(Integer.parseInt(this.txtBuscarHabitacion.getText()));
                    if (posicion == -1) {
                        JOptionPane.showMessageDialog(null, "No se encontro ningun resultado con el numero de habitacion ingresado");
                    } else {
                        // TODO add your handling code here:
                        objHabitacion = PantallaPrincipal.gHab.getObjHabitacion(posicion);

                        this.txtID.setText(Integer.toString(objHabitacion.getIdHabitacion()));
                        this.txtNumeroHabitacion.setText(Integer.toString(objHabitacion.getNumHabitacion()));
                        this.txtNumPiso.setText(Integer.toString(objHabitacion.getNumPiso()));
                        this.txtCapacidad.setText(Integer.toString(objHabitacion.getCapacidad()));
                        this.txtPrecioDia.setText(Double.toString(objHabitacion.getPrecio()));
                        this.txtDisponibilidad.setText(objHabitacion.getDescripcion());
                        this.txtDescripcion.setText(objHabitacion.getDescripcion());

                        this.btnEditar.setEnabled(true);
                        this.btnEliminar.setEnabled(true);
                    }
                }
            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:

        int index = this.cbxCategoria.getSelectedIndex();
        CategoriaHabitacion categoria = PantallaPrincipal.gCatHab.objCategoriaHabitacion(index);

        this.txtID.setText(Integer.toString(PantallaPrincipal.gHab.id()));
        this.txtNumPiso.setText("");
        this.txtNumeroHabitacion.setText("");
        this.txtPrecioDia.setText(Double.toString(categoria.getPrecioDia()));
        this.txtCapacidad.setText(Integer.toString(categoria.getCapacidad()));
        this.txtDescripcion.setText(categoria.getCaracteristicas());
        this.txtDisponibilidad.setText("Disponible");

        this.txtDisponibilidad.setEnabled(true);
        this.txtNumPiso.setEnabled(true);
        this.txtNumeroHabitacion.setEnabled(true);

        this.btnGuardar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(true);

        agregando = true;


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.btnNuevo.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (agregando) {

                int id, numHab, numPiso, capacidad;
                CategoriaHabitacion categoria;
                double precio;
                String disponibilidad, caracteristicas;

                //Recuperar el objeto categorai
                int index = this.cbxCategoria.getSelectedIndex();
                categoria = PantallaPrincipal.gCatHab.objCategoriaHabitacion(index);

                //Obtener los valores del combobox
                id = PantallaPrincipal.gHab.id();
                numHab = Integer.parseInt(this.txtNumeroHabitacion.getText());
                numPiso = Integer.parseInt(this.txtNumPiso.getText());
                capacidad = categoria.getCapacidad();
                precio = categoria.getPrecioDia();
                disponibilidad = this.txtDisponibilidad.getText();
                caracteristicas = this.txtDescripcion.getText();
                //Instanciar el objeto Habitacion

                Habitacion hab = new Habitacion();

                //Setear los valores
                hab.setIdHabitacion(id);
                hab.setNumHabitacion(numHab);
                hab.setNumPiso(numPiso);
                hab.setCapacidad(capacidad);
                hab.setCategoria(categoria);
                hab.setPrecio(precio);
                hab.setDisponibilidad(disponibilidad);
                hab.setDescripcion(caracteristicas);

                //Agregarlo a la lista
                int comprobarNumHabitacion;
                comprobarNumHabitacion = PantallaPrincipal.gHab.buscarPorNumeroHabitacion(Integer.parseInt(this.txtNumeroHabitacion.getText()));

                if (comprobarNumHabitacion == -1) {
                    PantallaPrincipal.gHab.agregarHabitacion(hab);
                    actualizarElementosEnTabla();
                    this.agregando = false;

                    this.btnGuardar.setEnabled(false);
                    this.btnEditar.setEnabled(false);
                    this.btnEliminar.setEnabled(false);
                    this.btnNuevo.setEnabled(true);
                    this.btnCancelar.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Ya hay una habitacion registrada con ese mismo numero");
                }

            } else {
                int id, numHab, numPiso, capacidad;
                CategoriaHabitacion categoria;
                double precio;
                String disponibilidad, caracteristicas;

                //Recuperar el objeto categoraiHabitacion
                int index = this.cbxCategoria.getSelectedIndex();
                categoria = PantallaPrincipal.gCatHab.objCategoriaHabitacion(index);

                //Obtener los valores del combobox
                id = PantallaPrincipal.gHab.id();
                numHab = Integer.parseInt(this.txtNumeroHabitacion.getText());
                numPiso = Integer.parseInt(this.txtNumPiso.getText());
                capacidad = categoria.getCapacidad();
                precio = categoria.getPrecioDia();
                disponibilidad = this.txtDisponibilidad.getText();
                caracteristicas = this.txtDescripcion.getText();
                //Instanciar el objeto Habitacion

                Habitacion objModificado = new Habitacion();

                //Setear los valores
                objModificado.setIdHabitacion(id);
                objModificado.setNumHabitacion(numHab);
                objModificado.setNumPiso(numPiso);
                objModificado.setCapacidad(capacidad);
                objModificado.setCategoria(categoria);
                objModificado.setPrecio(precio);
                objModificado.setDisponibilidad(disponibilidad);
                objModificado.setDescripcion(caracteristicas);

                //Agregarlo a la lista
                int comprobarNumHabitacion;
                comprobarNumHabitacion = PantallaPrincipal.gHab.buscarPorNumeroHabitacion(Integer.parseInt(this.txtNumeroHabitacion.getText()));
               Habitacion obj = PantallaPrincipal.gHab.getObjHabitacion(posicionElemento);
               
                if (comprobarNumHabitacion == -1 ||  numHab == obj.getNumHabitacion()) {
                    PantallaPrincipal.gHab.modificar(posicionElemento, objModificado);
                    actualizarElementosEnTabla();
                    this.btnGuardar.setEnabled(false);
                    this.btnEditar.setEnabled(false);
                    this.btnEliminar.setEnabled(false);
                    this.btnNuevo.setEnabled(true);

                } else {
                    JOptionPane.showMessageDialog(null, "Ya hay una habitacion registrada con ese mismo numero");
                }

            }
            this.btnCancelar.setEnabled(false);
            this.btnEditar.setEnabled(false);
            this.btnEliminar.setEnabled(false);
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.txtDisponibilidad.setEnabled(true);
        this.txtNumPiso.setEnabled(true);
        this.txtNumeroHabitacion.setEnabled(true);

        this.agregando = false;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.txtDescripcion.setVisible(true);
        this.btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Eliminar habitacion", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            PantallaPrincipal.gHab.eliminarHabitacion(this.posicionElemento);
            this.actualizarElementosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPrecioDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioDiaMouseClicked
        // TODO add your handling code here:
        this.txtPrecioDia.setText("");
    }//GEN-LAST:event_txtPrecioDiaMouseClicked

    private void txtBuscarHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarHabitacionMouseClicked
        // TODO add your handling code here:
        this.txtBuscarHabitacion.setText("");
    }//GEN-LAST:event_txtBuscarHabitacionMouseClicked

    private void jtblHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblHabitacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblHabitacionMouseClicked

    private void jtblHabitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblHabitacionMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.posicionElemento = this.jtblHabitacion.getSelectedRow();
        Habitacion objHab = PantallaPrincipal.gHab.getObjHabitacion(posicionElemento);

        this.txtID.setText(Integer.toString(objHab.getIdHabitacion()));
        this.txtNumeroHabitacion.setText(Integer.toString(objHab.getNumHabitacion()));
        this.txtNumPiso.setText(Integer.toString(objHab.getNumPiso()));
        this.txtCapacidad.setText(Integer.toString(objHab.getCapacidad()));
        this.txtPrecioDia.setText(Double.toString(objHab.getPrecio()));
        this.txtDisponibilidad.setText(objHab.getDescripcion());
        this.txtDescripcion.setText(objHab.getDescripcion());

        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);

    }//GEN-LAST:event_jtblHabitacionMousePressed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
        this.txtID.setText(Integer.toString(PantallaPrincipal.gHab.id()));
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarHabitacionActionPerformed
        // TODO add your handling code here:
        this.txtBuscarHabitacion.setText("");
    }//GEN-LAST:event_txtBuscarHabitacionActionPerformed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed

    }//GEN-LAST:event_btnBuscarMousePressed

    private void txtNumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroHabitacionActionPerformed
        // TODO add your handling code here:
        this.txtNumeroHabitacion.setText("");
    }//GEN-LAST:event_txtNumeroHabitacionActionPerformed

    private void txtNumPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPisoActionPerformed
        // TODO add your handling code here:
        this.txtNumPiso.setText("");
    }//GEN-LAST:event_txtNumPisoActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void txtCapacidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCapacidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadMouseClicked

    private void txtDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMouseClicked
        // TODO add your handling code here:
        this.txtDescripcion.setText("");
    }//GEN-LAST:event_txtDescripcionMouseClicked

    private void txtPrecioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioDiaActionPerformed
        // TODO add your handling code here:
        this.txtPrecioDia.setText("");
    }//GEN-LAST:event_txtPrecioDiaActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
        this.txtCapacidad.setText("");
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMouseClicked

    private void txtDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisponibilidadActionPerformed

    private void cbxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCategoriaItemStateChanged
        // TODO add your handling code here:
        int index = this.cbxCategoria.getSelectedIndex();
        CategoriaHabitacion categoria = PantallaPrincipal.gCatHab.objCategoriaHabitacion(index);

        this.txtID.setText(Integer.toString(PantallaPrincipal.gHab.id()));
        this.txtNumPiso.setText("");
        this.txtNumeroHabitacion.setText("");
        this.txtPrecioDia.setText(Double.toString(categoria.getPrecioDia()));
        this.txtCapacidad.setText(Integer.toString(categoria.getCapacidad()));
        this.txtDescripcion.setText(categoria.getCaracteristicas());
        this.txtDisponibilidad.setText("Disponible");
    }//GEN-LAST:event_cbxCategoriaItemStateChanged

    private void cbxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxBuscarActionPerformed

    private void cbxBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBuscarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBuscarItemStateChanged

    private void btnReportes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes3ActionPerformed
        // TODO add your handling code here:

        String nombreArchivo = "Habitaciones";
        String contenido = PantallaPrincipal.gHab.getInformacionGestion();
        String ruta = "Reportes/" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }

    }//GEN-LAST:event_btnReportes3ActionPerformed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID", "Num. habitación", "num. piso", "Categoría", "Precio por dia", "Capacidad", "Disponibilidad", "Descripcion"};
        DefaultTableModel tablaHabitaciones = new DefaultTableModel(PantallaPrincipal.gHab.getArrayGestion(), tituloColumnas);

        this.jtblHabitacion.setModel(tablaHabitaciones);
        AdminSerializacion.guardar(PantallaPrincipal.gHab, "objHabitacion.obj");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton btnReportes2;
    private javax.swing.JButton btnReportes3;
    private javax.swing.JComboBox<String> cbxBuscar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblHabitacion;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCancelar1;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEditar1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblImagenID;
    private javax.swing.JLabel lblImagenID1;
    private javax.swing.JLabel lblImagenID2;
    private javax.swing.JLabel lblImagenID3;
    private javax.swing.JLabel lblImagenID4;
    private javax.swing.JLabel lblImagenID5;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblNumeroHabitacion;
    private javax.swing.JLabel lblNumeroHabitacion1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JTextField txtBuscarHabitacion;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDisponibilidad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNumPiso;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtPrecioDia;
    // End of variables declaration//GEN-END:variables
}
