/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Producto;
import clases.Proveedor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;
import utilitario.AdminSerializacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitario.AdminFechas;

/**
 *
 * @author aarve
 */
public class GuiProducto extends javax.swing.JInternalFrame {

    private boolean agregando = false;
    private int posicionElemento;

    /**
     * Creates new form GuiCategoriaHabitacion
     */
    public GuiProducto() {

        initComponents();
        cbxProveedor.setModel(PantallaPrincipal.gProv.getComboboxModel());
        this.actualizarElementosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblImagenID = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblCategoria1 = new javax.swing.JLabel();
        fontoTexto = new javax.swing.JLabel();
        lblCategoria2 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        lblCategoria3 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        lblImagenID1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblNuevo = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEditar1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JTextField();
        fontoTexto1 = new javax.swing.JLabel();
        lblCategoria5 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        lblImagenID2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCategoria6 = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxMes = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblImagenID4 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblCancelar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(670, 730));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setText("000");
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 55, 40, 10));

        lblImagenID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 60, 60));

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Nombre del producto");
        jPanel2.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        txtNombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreProducto.setText("Nombre del producto");
        txtNombreProducto.setBorder(null);
        txtNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreProductoMouseClicked(evt);
            }
        });
        txtNombreProducto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNombreProductoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 30));

        lblCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setText("Descripción");
        jPanel2.add(lblCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 30));

        fontoTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 250, 50));

        lblCategoria2.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria2.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setText("Proveedor");
        jPanel2.add(lblCategoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, 30));

        cbxProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cbxProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 100, -1));

        lblCategoria3.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria3.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria3.setText("Existencia");
        jPanel2.add(lblCategoria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 30));

        txtExistencia.setBackground(new java.awt.Color(255, 255, 255));
        txtExistencia.setForeground(new java.awt.Color(0, 0, 0));
        txtExistencia.setText("0.00");
        txtExistencia.setBorder(null);
        txtExistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExistenciaMouseClicked(evt);
            }
        });
        jPanel2.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 405, 40, 10));

        lblImagenID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 60, 60));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 1 nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 2 nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 60, 40));

        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Nuevo");
        jPanel2.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setText("Reportes");
        jPanel2.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 60, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 60, 40));

        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setText("Guardar");
        jPanel2.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 1.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 70, 40));

        lblEditar1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar1.setText("Eliminar");
        jPanel2.add(lblEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 50, 20));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 2.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setEnabled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 3.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 1.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 70, 40));

        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");
        jPanel2.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 50, 20));

        lblCategoria4.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria4.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria4.setText("Unidad de medida");
        jPanel2.add(lblCategoria4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        txtUnidadMedida.setBackground(new java.awt.Color(255, 255, 255));
        txtUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));
        txtUnidadMedida.setText("Unidad de medida del producto");
        txtUnidadMedida.setBorder(null);
        txtUnidadMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadMedidaMouseClicked(evt);
            }
        });
        txtUnidadMedida.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtUnidadMedidaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadMedidaActionPerformed(evt);
            }
        });
        jPanel2.add(txtUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 220, 30));

        fontoTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 250, 50));

        lblCategoria5.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria5.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria5.setText("Precio venta");
        jPanel2.add(lblCategoria5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, 30));

        txtPrecioVenta.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecioVenta.setText("0.00");
        txtPrecioVenta.setBorder(null);
        txtPrecioVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioVentaMouseClicked(evt);
            }
        });
        jPanel2.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 405, 40, 10));

        lblImagenID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 60, 60));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setText("Descripcion");
        txtDescripcion.setBorder(null);
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDescripcionMouseClicked(evt);
            }
        });
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 50));

        lblCategoria6.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria6.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria6.setText("Fecha de vencimiento");
        jPanel2.add(lblCategoria6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 20));

        cbxDia.setBackground(new java.awt.Color(255, 255, 255));
        cbxDia.setForeground(new java.awt.Color(0, 0, 0));
        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(cbxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 50, 20));

        jLabel5.setText("Dia");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 30, 20));

        jLabel6.setText("Mes");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 30, -1));

        cbxMes.setBackground(new java.awt.Color(255, 255, 255));
        cbxMes.setForeground(new java.awt.Color(0, 0, 0));
        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cbxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 80, 20));

        jLabel7.setText("Año");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 30, -1));

        txtAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtAnio.setForeground(new java.awt.Color(0, 0, 0));
        txtAnio.setText("000");
        txtAnio.setBorder(null);
        txtAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAnioMousePressed(evt);
            }
        });
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 485, 40, 10));

        lblImagenID4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 60, 20));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 60, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 450, 70));

        lblCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar1.setText("Cancelar");
        jPanel2.add(lblCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProductosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 620, 240));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 3.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 2.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, 50));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setText("Buscar por ID");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 370, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 670, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.posicionElemento = PantallaPrincipal.gProd.buscarPorId(Integer.parseInt(this.txtBuscar.getText()));
        if (posicionElemento == -1) {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados con los parametros de busqueda");
        } else {
            Producto obj = PantallaPrincipal.gProd.getProducto(posicionElemento);
            this.txtAnio.setText(Integer.toString(obj.getFechaVencimiento().getYear()));//Buscar un metodo que obtenga un determinado dato de un Date.
            this.txtDescripcion.setText(obj.getDescripcionProducto());
            this.txtExistencia.setText(Integer.toString(obj.getExistencia()));
            this.txtID.setText(Integer.toString(obj.getIdProducto()));
            this.txtNombreProducto.setText(obj.getNombreProducto());
            this.txtPrecioVenta.setText(Float.toString(obj.getPrecioVenta()));
            this.txtUnidadMedida.setText(obj.getuMedida());
            // this.cbxDia.setSelectedIndex(obj.getFechaVencimiento().getDay() - 1);
            // this.cbxMes.setSelectedIndex(obj.getFechaVencimiento().getMonth() - 1);
            // int posicionProveedor = obj.getProvedor().getIdProveedor();
            // this.cbxProveedor.setSelectedIndex(posicionProveedor);

            this.btnEditar.setEnabled(true);
            this.btnEliminar.setEnabled(true);
            this.btnGuardar.setEnabled(false);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:

        this.agregando = true;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnCancelar.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            // TODO add your handling code here:
            String nombre, descripcion, uMedida;
            int existencia;
            Proveedor objProveedor;
            float precioVenta;
            Date fechaVencimiento;

            if (agregando) {
                nombre = this.txtNombreProducto.getText();
                descripcion = this.txtDescripcion.getText();
                uMedida = this.txtUnidadMedida.getText();
                existencia = Integer.parseInt(this.txtExistencia.getText());

                //Obtener objeto proveedor seleccionado de los combobox
                int posicion = this.cbxProveedor.getSelectedIndex();
                objProveedor = PantallaPrincipal.gProv.getObjProveedor(posicion);

                precioVenta = Float.parseFloat(this.txtPrecioVenta.getText());
                //Obtener la fecha de los combobox
                String dia, mes, anio;
                dia = Integer.toString(this.cbxDia.getSelectedIndex());
                mes = Integer.toString(this.cbxMes.getSelectedIndex());
                anio = this.txtAnio.getText();

                fechaVencimiento = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);

                //crear y Agregar el objeto a la gestion
                Producto objProducto = new Producto();
                objProducto.setDescripcionProducto(descripcion);
                objProducto.setExistencia(existencia);
                objProducto.setFechaVencimiento(fechaVencimiento);
                //objProducto.setIdProducto(id);
                objProducto.setNombreProducto(nombre);
                objProducto.setPrecioVenta(precioVenta);
                objProducto.setProvedor(objProveedor);
                objProducto.setuMedida(uMedida);

                PantallaPrincipal.gProd.agregarProducto(objProducto);

                actualizarElementosEnTabla();
                this.agregando = false;
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnCancelar.setEnabled(false);

            } else {
                nombre = this.txtNombreProducto.getText();
                descripcion = this.txtDescripcion.getText();
                uMedida = this.txtUnidadMedida.getText();
                existencia = Integer.parseInt(this.txtExistencia.getText());

                //Obtener objeto proveedor seleccionado de los combobox
                int posicion = this.cbxProveedor.getSelectedIndex();
                objProveedor = PantallaPrincipal.gProv.getObjProveedor(posicion);

                precioVenta = Float.parseFloat(this.txtPrecioVenta.getText());
                //Obtener la fecha de los combobox
                String dia, mes, anio;
                dia = Integer.toString(this.cbxDia.getSelectedIndex());
                mes = Integer.toString(this.cbxMes.getSelectedIndex());
                anio = this.txtAnio.getText();

                fechaVencimiento = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);

                //crear y Agregar el objeto a la gestion
                Producto objModificado = new Producto();
                objModificado.setDescripcionProducto(descripcion);
                objModificado.setExistencia(existencia);
                objModificado.setFechaVencimiento(fechaVencimiento);
                //objModificado.setIdProducto(id);
                objModificado.setNombreProducto(nombre);
                objModificado.setPrecioVenta(precioVenta);
                objModificado.setProvedor(objProveedor);
                objModificado.setuMedida(uMedida);

                PantallaPrincipal.gProd.modificarHabitacion(objModificado, posicionElemento);

                actualizarElementosEnTabla();

                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
            this.btnCancelar.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al registrar "+e);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.agregando = false;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            PantallaPrincipal.gProd.eliminarProducto(this.posicionElemento);
            this.actualizarElementosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtNombreProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMouseClicked
        // TODO add your handling code here:
        this.txtNombreProducto.setText("");
    }//GEN-LAST:event_txtNombreProductoMouseClicked

    private void txtExistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExistenciaMouseClicked
        // TODO add your handling code here:
        this.txtExistencia.setText("");
    }//GEN-LAST:event_txtExistenciaMouseClicked

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        // TODO add your handling code here:
        this.txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtNombreProductoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNombreProductoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoCaretPositionChanged

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosMouseClicked

    private void tblProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMousePressed
        // TODO add your handling code here:
        this.posicionElemento = tblProductos.getSelectedRow();
        Producto obj = PantallaPrincipal.gProd.getProducto(posicionElemento);
        this.txtAnio.setText(Integer.toString(obj.getFechaVencimiento().getYear()));//Buscar un metodo que obtenga un determinado dato de un Date.
        this.txtDescripcion.setText(obj.getDescripcionProducto());
        this.txtExistencia.setText(Integer.toString(obj.getExistencia()));
        this.txtID.setText(Integer.toString(obj.getIdProducto()));
        this.txtNombreProducto.setText(obj.getNombreProducto());
        this.txtPrecioVenta.setText(Float.toString(obj.getPrecioVenta()));
        this.txtUnidadMedida.setText(obj.getuMedida());
        this.cbxDia.setSelectedIndex(obj.getFechaVencimiento().getDay() - 1);
        this.cbxMes.setSelectedIndex(obj.getFechaVencimiento().getMonth() - 1);
        int posicionProveedor = obj.getProvedor().getIdProveedor();
        this.cbxProveedor.setSelectedIndex(posicionProveedor);


    }//GEN-LAST:event_tblProductosMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        this.txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed

    }//GEN-LAST:event_btnBuscarMousePressed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtUnidadMedidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadMedidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMedidaMouseClicked

    private void txtUnidadMedidaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtUnidadMedidaCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMedidaCaretPositionChanged

    private void txtUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMedidaActionPerformed

    private void txtPrecioVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaMouseClicked

    private void txtDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionMouseClicked

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioMousePressed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

        String nombreArchivo = "Productos";
        String contenido = PantallaPrincipal.gProd.getInformacionGestion();
        String ruta = "Reportes/" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID", "Producto", "Unidad medida", "Fecha de vencimiento", "Existencia", "precio  Venta", "Proveedor"};
        DefaultTableModel tablaProducto = new DefaultTableModel(PantallaPrincipal.gProd.getArrayGestion(), tituloColumnas);

        this.tblProductos.setModel(tablaProducto);
        AdminSerializacion.guardar(PantallaPrincipal.gProd, "objProductos.obj");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel fontoTexto;
    private javax.swing.JLabel fontoTexto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCancelar1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCategoria3;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria5;
    private javax.swing.JLabel lblCategoria6;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEditar1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImagenID;
    private javax.swing.JLabel lblImagenID1;
    private javax.swing.JLabel lblImagenID2;
    private javax.swing.JLabel lblImagenID4;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
