/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Empleado;
import clases.Habitacion;
import clases.Reserva;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitario.AdminFechas;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class GuiReserva extends javax.swing.JInternalFrame {

    private boolean agregando = false;
    private int posicionElemento;
    private int id;

    /**
     * Creates new form GuiCategoriaHabitacion
     */
    public GuiReserva() {

        initComponents();
        this.cbxEmpleado.setModel(PantallaPrincipal.gEmpleado.getComboboxModel());
        this.cbxHabitacion.setModel(PantallaPrincipal.gHab.getComboboxModel());
        actualizarElementosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupEstadoCivil = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblCorreo8 = new javax.swing.JLabel();
        cbxFechaEgreso = new javax.swing.JComboBox<>();
        cbxMesEgreso = new javax.swing.JComboBox<>();
        cbxMesIngreso = new javax.swing.JComboBox<>();
        cbxFechaIngreso = new javax.swing.JComboBox<>();
        txtNumTelefono = new javax.swing.JTextField();
        fontoTexto5 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        fontoTexto4 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        fontoTexto2 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        fontoTexto = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblNuevo = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEditar1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        lblCategoria7 = new javax.swing.JLabel();
        lblCorreo4 = new javax.swing.JLabel();
        txtPrecioEstadia = new javax.swing.JTextField();
        lblImagenID3 = new javax.swing.JLabel();
        txtNumIdentidad = new javax.swing.JTextField();
        fontoTexto8 = new javax.swing.JLabel();
        lblCorreo5 = new javax.swing.JLabel();
        lblCorreo6 = new javax.swing.JLabel();
        cbxHabitacion = new javax.swing.JComboBox<>();
        lblCorreo7 = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblImagenID2 = new javax.swing.JLabel();
        lblCorreo9 = new javax.swing.JLabel();
        cbxEmpleado = new javax.swing.JComboBox<>();
        spnNumHuesped = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCorreo10 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        lblCancelar1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        fontoTexto9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario de Reservas de habitacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(670, 730));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo8.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo8.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo8.setText("Fecha de egreso");
        jPanel2.add(lblCorreo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        cbxFechaEgreso.setBackground(new java.awt.Color(255, 255, 255));
        cbxFechaEgreso.setForeground(new java.awt.Color(0, 0, 0));
        cbxFechaEgreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxFechaEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFechaEgresoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxFechaEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 50, 20));

        cbxMesEgreso.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesEgreso.setForeground(new java.awt.Color(0, 0, 0));
        cbxMesEgreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cbxMesEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, 20));

        cbxMesIngreso.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesIngreso.setForeground(new java.awt.Color(0, 0, 0));
        cbxMesIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cbxMesIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 20));

        cbxFechaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        cbxFechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        cbxFechaIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFechaIngresoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 50, 20));

        txtNumTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtNumTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtNumTelefono.setText("número de teléfono");
        txtNumTelefono.setBorder(null);
        txtNumTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumTelefonoMouseClicked(evt);
            }
        });
        txtNumTelefono.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNumTelefonoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, 30));

        fontoTexto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, 50));

        lblCorreo1.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo1.setText("Número de teléfono");
        jPanel2.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 20));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo Electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtCorreoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 30));

        fontoTexto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 50));

        lblCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo.setText("Correo electronico");
        jPanel2.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Datos del Huesped");
        jPanel2.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerApellido.setText("Primer apellido");
        txtPrimerApellido.setBorder(null);
        txtPrimerApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerApellidoMouseClicked(evt);
            }
        });
        txtPrimerApellido.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtPrimerApellidoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 220, 30));

        fontoTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 50));

        txtPrimerNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimerNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerNombre.setText("Primer nombre");
        txtPrimerNombre.setBorder(null);
        txtPrimerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMousePressed(evt);
            }
        });
        txtPrimerNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtPrimerNombreCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        fontoTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 50));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 1 nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 2 nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 60, 40));

        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Nuevo");
        jPanel2.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setText("Cancelar");
        jPanel2.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 60, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 60, 40));

        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setText("Guardar");
        jPanel2.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 1.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 70, 40));

        lblEditar1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar1.setText("Eliminar");
        jPanel2.add(lblEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 50, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 2.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setEnabled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 3.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 1.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 70, 40));

        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");
        jPanel2.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 595, 40, 20));

        lblCategoria4.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria4.setForeground(new java.awt.Color(0, 153, 153));
        lblCategoria4.setText("Nombre");
        jPanel2.add(lblCategoria4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblCategoria7.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCategoria7.setForeground(new java.awt.Color(0, 153, 153));
        lblCategoria7.setText("Apellido");
        jPanel2.add(lblCategoria7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 20));

        lblCorreo4.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo4.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo4.setText("Fecha de ingreso");
        jPanel2.add(lblCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 20));

        txtPrecioEstadia.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioEstadia.setForeground(new java.awt.Color(153, 0, 0));
        txtPrecioEstadia.setText("000");
        txtPrecioEstadia.setBorder(null);
        txtPrecioEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEstadiaActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecioEstadia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 40, 10));

        lblImagenID3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 30));

        txtNumIdentidad.setBackground(new java.awt.Color(255, 255, 255));
        txtNumIdentidad.setForeground(new java.awt.Color(0, 0, 0));
        txtNumIdentidad.setText("Numero de tarjeta de identidad");
        txtNumIdentidad.setBorder(null);
        txtNumIdentidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumIdentidadMouseClicked(evt);
            }
        });
        txtNumIdentidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNumIdentidadCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNumIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIdentidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 30));

        fontoTexto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel2.add(fontoTexto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 50));

        lblCorreo5.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo5.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo5.setText("Numero de identidad");
        jPanel2.add(lblCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        lblCorreo6.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo6.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo6.setText("Habitacion");
        jPanel2.add(lblCorreo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 80, 20));

        cbxHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        cbxHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(cbxHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 100, 20));

        lblCorreo7.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo7.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo7.setText("Precio de estadia");
        jPanel2.add(lblCorreo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 120, 20));

        lblID1.setBackground(new java.awt.Color(255, 255, 255));
        lblID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(255, 255, 255));
        lblID1.setText("ID reserva");
        jPanel2.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 20));

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setText("000");
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 10));

        lblImagenID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel2.add(lblImagenID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 60, 70));

        lblCorreo9.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo9.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo9.setText("Empleado");
        jPanel2.add(lblCorreo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 80, 20));

        cbxEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        cbxEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(cbxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 100, 20));
        jPanel2.add(spnNumHuesped, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 50, 30));

        jLabel2.setText("Mes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel3.setText("Dia");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel4.setText("Dia");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel5.setText("Mes");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        lblCorreo10.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo10.setForeground(new java.awt.Color(0, 153, 153));
        lblCorreo10.setText("Num. ocupantes");
        jPanel2.add(lblCorreo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, 20));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 60, 40));

        lblCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar1.setText("Reporte");
        jPanel2.add(lblCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 450, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 730));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de reservas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblReservasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblReservas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 810, 440));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 3.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 2.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 50));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setText("Buscar por Num identidad");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 20));

        fontoTexto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja de texto.png"))); // NOI18N
        jPanel1.add(fontoTexto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 370, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 820, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        this.posicionElemento = PantallaPrincipal.gRsv.buscarPorNumIdentidadCliente(txtBuscar.getText());
        if (posicionElemento == -1) {
            JOptionPane.showMessageDialog(null, "No se encontro reservas con los parametros de busqueda");
        } else {
            Reserva objReserva = PantallaPrincipal.gRsv.getObjetoReserva(posicionElemento);

            this.txtCorreo.setText(objReserva.getCorreo());
            this.txtId.setText(Integer.toString(objReserva.getIdReserva()));
            this.txtNumIdentidad.setText(objReserva.getNumIdentidad());
            this.txtNumTelefono.setText(objReserva.getTelefono());
            this.txtPrimerApellido.setText(objReserva.getApellido());
            this.txtPrimerNombre.setText(objReserva.getNombre());
            this.txtPrecioEstadia.setText(Double.toString(objReserva.getPrecioEstadia()));

            //Encontrar posicion del objeto empleado en el combobox
            int idempleado = objReserva.getDatosEmpleadoEncargado().getIdEmpleado();
            int posicion = PantallaPrincipal.gEmpleado.buscarPorId(idempleado);
            this.cbxEmpleado.setSelectedIndex(posicion);
            //this.cbxFechaEgreso.setSelectedIndex();
            //this.cbxFechaIngreso.setSelectedIndex(WIDTH);

            //Encontrar la posicion del objeto habitacion en la lista
            int idHabitacion = objReserva.getDatosHabitacion().getIdHabitacion();
            int posicionObjHabitacion = PantallaPrincipal.gHab.buscarPorId(idHabitacion);
            this.cbxHabitacion.setSelectedIndex(posicionObjHabitacion);

            //this.cbxMesEgreso.setSelectedIndex(WIDTH);
            //this.cbxMesIngreso.setSelectedIndex(WIDTH);
            this.btnEditar.setEnabled(true);
            this.btnEliminar.setEnabled(true);
            this.btnGuardar.setEnabled(false);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.agregando = true;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnCancelar.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.btnNuevo.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // TODO add your handling code here:
        try {
            if (agregando) {
                int idReserva;
                String nombre, apellido, correo, telefono, numIdentidad;
                Habitacion datosHabitacion;
                Empleado datosEmpleadoEncargado;
                int numHuesped;
                double precio;
                Date fechaReserva;
                Date fechaIngreso;
                Date fechaEgreso;
                //Obtener los objetos empleado y Habitacion
                int posicionEmpleado = this.cbxEmpleado.getSelectedIndex();
                datosEmpleadoEncargado = PantallaPrincipal.gEmpleado.getObjetoEmpleado(posicionEmpleado);
                int posicionHabitacion = this.cbxHabitacion.getSelectedIndex();
                datosHabitacion = PantallaPrincipal.gHab.getObjHabitacion(posicionHabitacion);

                //Obtener los elementos de los textBox
                idReserva = PantallaPrincipal.gRsv.AsignarId();
                nombre = this.txtPrimerNombre.getText();
                apellido = this.txtPrimerApellido.getText();
                correo = this.txtCorreo.getText();
                telefono = this.txtNumTelefono.getText();
                numIdentidad = this.txtNumIdentidad.getText();
                numHuesped = (int) this.spnNumHuesped.getValue();
                fechaReserva = AdminFechas.getFechaActual();
                int dia;
                int mes;
                String anio = AdminFechas.getAnioActualString();

                //Para la fecha de ingreso
                dia = cbxFechaIngreso.getSelectedIndex() + 1;
                mes = cbxMesIngreso.getSelectedIndex() + 1;
                fechaIngreso = AdminFechas.stringToDate(Integer.toString(dia) + "-" + Integer.toString(mes) + "-" + anio);

                //Para la fecha de egreso
                dia = cbxFechaEgreso.getSelectedIndex() + 1;
                mes = cbxMesEgreso.getSelectedIndex() + 1;
                fechaEgreso = AdminFechas.stringToDate(Integer.toString(dia) + "-" + Integer.toString(mes) + "-" + anio);

//Crear el objeto
                Reserva objReserva = new Reserva();
                objReserva.setApellido(apellido);
                objReserva.setCorreo(correo);
                objReserva.setDatosEmpleadoEncargado(datosEmpleadoEncargado);
                objReserva.setDatosHabitacion(datosHabitacion);
                objReserva.setFechaEgreso(fechaEgreso);
                objReserva.setFechaIngreso(fechaIngreso);
                objReserva.setFechaReserva(fechaReserva);
                objReserva.setIdReserva(idReserva);
                objReserva.setNombre(nombre);
                objReserva.setNumHuesped(numHuesped);
                objReserva.setNumIdentidad(numIdentidad);
                objReserva.setTelefono(telefono);
                precio = PantallaPrincipal.gRsv.precioEstadia(objReserva);
                objReserva.setPrecioEstadia(precio);

                //Agregar el objeto a la gestion
                if (objReserva.getNumHuesped() > objReserva.getDatosHabitacion().getCategoria().getCapacidad()) {
                    JOptionPane.showMessageDialog(null, "El numero de huespedes sobrepasa la capacidad de la habitacion");
                } else {
                    PantallaPrincipal.gRsv.agregarReserva(objReserva);
                    this.txtPrecioEstadia.setText(Double.toString(PantallaPrincipal.gRsv.precioEstadia(objReserva)));
                }

                actualizarElementosEnTabla();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnCancelar.setEnabled(false);
                this.agregando = false;
            } else {

                int idReserva;
                String nombre, apellido, correo, telefono, numIdentidad;
                Habitacion datosHabitacion;
                Empleado datosEmpleadoEncargado;
                String habitacion;
                String empleado;
                int numHuesped;
                double precio;
                Date fechaReserva;
                Date fechaIngreso;
                Date fechaEgreso;
                //Obtener los objetos empleado y Habitacion
                int posicionEmpleado = this.cbxEmpleado.getSelectedIndex();
                datosEmpleadoEncargado = PantallaPrincipal.gEmpleado.getObjetoEmpleado(posicionEmpleado);
                int posicionHabitacion = this.cbxHabitacion.getSelectedIndex();
                datosHabitacion = PantallaPrincipal.gHab.getObjHabitacion(posicionHabitacion);

                //Obtener los elementos de los textBox
                idReserva = PantallaPrincipal.gRsv.AsignarId();
                nombre = this.txtPrimerNombre.getText();
                apellido = this.txtPrimerApellido.getText();
                correo = this.txtCorreo.getText();
                telefono = this.txtNumTelefono.getText();
                numIdentidad = this.txtNumIdentidad.getText();
                habitacion = datosHabitacion.getCategoria().getNombreCategoria();
                empleado = datosEmpleadoEncargado.getpNombre() + " " + datosEmpleadoEncargado.getpApellido();
                numHuesped = (int) this.spnNumHuesped.getValue();
                fechaReserva = AdminFechas.getFechaActual();
                int dia;
                int mes;
                String anio = AdminFechas.getAnioActualString();

                //Para la fecha de ingreso
                dia = cbxFechaIngreso.getSelectedIndex() + 1;
                mes = cbxMesIngreso.getSelectedIndex() + 1;
                fechaIngreso = AdminFechas.stringToDate(Integer.toString(dia) + "-" + Integer.toString(mes) + "-" + anio);

                //Para la fecha de egreso
                dia = cbxFechaEgreso.getSelectedIndex() + 1;
                mes = cbxMesEgreso.getSelectedIndex() + 1;
                fechaEgreso = AdminFechas.stringToDate(Integer.toString(dia) + "-" + Integer.toString(mes) + "-" + anio);

                precio = Double.parseDouble(this.txtPrecioEstadia.getText());
                //Crear el objeto
                Reserva objModificado = new Reserva();
                objModificado.setApellido(apellido);
                objModificado.setCorreo(correo);
                objModificado.setDatosEmpleadoEncargado(datosEmpleadoEncargado);
                objModificado.setDatosHabitacion(datosHabitacion);
                objModificado.setFechaEgreso(fechaEgreso);
                objModificado.setFechaIngreso(fechaIngreso);
                objModificado.setFechaReserva(fechaReserva);
                objModificado.setIdReserva(idReserva);
                objModificado.setNombre(nombre);
                objModificado.setNumHuesped(numHuesped);
                objModificado.setNumIdentidad(numIdentidad);
                objModificado.setTelefono(telefono);
                precio = PantallaPrincipal.gRsv.precioEstadia(objModificado);
                objModificado.setPrecioEstadia(precio);

                //Agregar el objeto a la gestion
                if (objModificado.getNumHuesped() > objModificado.getDatosHabitacion().getCategoria().getCapacidad()) {
                    JOptionPane.showMessageDialog(null, "El numero de huespedes sobrepasa la capacidad de la habitacion");
                } else {
                    this.txtPrecioEstadia.setText(Double.toString(PantallaPrincipal.gRsv.precioEstadia(objModificado)));
                    PantallaPrincipal.gRsv.modificarReserva(posicionEmpleado, objModificado);
                }

                actualizarElementosEnTabla();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnNuevo.setEnabled(true);

            }

            this.btnCancelar.setEnabled(false);

        } catch (Exception e) {

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        this.agregando = false;
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Eliminar reserva", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            PantallaPrincipal.gRsv.eliminarReserva(posicionElemento);
            this.actualizarElementosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed

    private void txtPrimerNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMouseClicked
        // TODO add your handling code here:
        this.txtPrimerNombre.setText("");
    }//GEN-LAST:event_txtPrimerNombreMouseClicked

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        // TODO add your handling code here:
        this.txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtPrimerNombreCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPrimerNombreCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreCaretPositionChanged

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblReservasMouseClicked

    private void tblReservasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMousePressed
        // TODO add your handling code here:
        this.posicionElemento = this.tblReservas.getSelectedRow();

        Reserva objReserva = PantallaPrincipal.gRsv.getObjetoReserva(posicionElemento);

        this.txtCorreo.setText(objReserva.getCorreo());
        this.txtId.setText(Integer.toString(objReserva.getIdReserva()));
        this.txtNumIdentidad.setText(objReserva.getNumIdentidad());
        this.txtNumTelefono.setText(objReserva.getTelefono());
        this.txtPrimerApellido.setText(objReserva.getApellido());
        this.txtPrimerNombre.setText(objReserva.getNombre());
        this.txtPrecioEstadia.setText(Double.toString(objReserva.getPrecioEstadia()));

        //Encontrar posicion del objeto empleado en el combobox
        int idempleado = objReserva.getDatosEmpleadoEncargado().getIdEmpleado();
        int posicion = PantallaPrincipal.gEmpleado.buscarPorId(idempleado);
        this.cbxEmpleado.setSelectedIndex(posicion);
        //this.cbxFechaEgreso.setSelectedIndex();
        //this.cbxFechaIngreso.setSelectedIndex(WIDTH);

        //Encontrar la posicion del objeto habitacion en la lista
        int idHabitacion = objReserva.getDatosHabitacion().getIdHabitacion();
        int posicionObjHabitacion = PantallaPrincipal.gHab.buscarPorId(idHabitacion);
        this.cbxHabitacion.setSelectedIndex(posicionObjHabitacion);

        //this.cbxMesEgreso.setSelectedIndex(WIDTH);
        //this.cbxMesIngreso.setSelectedIndex(WIDTH);
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnGuardar.setEnabled(false);


    }//GEN-LAST:event_tblReservasMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed

    }//GEN-LAST:event_btnBuscarMousePressed

    private void txtPrimerApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerApellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoMouseClicked

    private void txtPrimerApellidoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPrimerApellidoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoCaretPositionChanged

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCorreoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoCaretPositionChanged

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNumTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumTelefonoMouseClicked
        // TODO add your handling code here:
        this.txtNumTelefono.setText("");
    }//GEN-LAST:event_txtNumTelefonoMouseClicked

    private void txtNumTelefonoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNumTelefonoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTelefonoCaretPositionChanged

    private void txtNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTelefonoActionPerformed

    private void txtNumIdentidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumIdentidadMouseClicked
        // TODO add your handling code here:
        this.txtNumIdentidad.setText("");
    }//GEN-LAST:event_txtNumIdentidadMouseClicked

    private void txtNumIdentidadCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNumIdentidadCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdentidadCaretPositionChanged

    private void txtNumIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdentidadActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtPrimerNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPrimerNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        this.txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtPrecioEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEstadiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEstadiaActionPerformed

    private void cbxFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFechaIngresoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxFechaIngresoActionPerformed

    private void cbxFechaEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFechaEgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFechaEgresoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

        String nombreArchivo = "Reservas";
        String contenido = PantallaPrincipal.gRsv.getInformacionGestion();
        String ruta = "Reportes\\" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID", "Huesped", "Tipo de habitacion", "Num. Habitacion", "Fecha de la reserva", "Fecha de ingreso", "Fecha de egreso", "Numero de huespedes"};
        DefaultTableModel tablaReserva = new DefaultTableModel(PantallaPrincipal.gRsv.getArrayGestion(), tituloColumnas);

        this.tblReservas.setModel(tablaReserva);
        AdminSerializacion.guardar(PantallaPrincipal.gRsv, "objReserva.obj");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrupEstadoCivil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cbxEmpleado;
    private javax.swing.JComboBox<String> cbxFechaEgreso;
    private javax.swing.JComboBox<String> cbxFechaIngreso;
    private javax.swing.JComboBox<String> cbxHabitacion;
    private javax.swing.JComboBox<String> cbxMesEgreso;
    private javax.swing.JComboBox<String> cbxMesIngreso;
    private javax.swing.JLabel fontoTexto;
    private javax.swing.JLabel fontoTexto2;
    private javax.swing.JLabel fontoTexto4;
    private javax.swing.JLabel fontoTexto5;
    private javax.swing.JLabel fontoTexto8;
    private javax.swing.JLabel fontoTexto9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCancelar1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria7;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo10;
    private javax.swing.JLabel lblCorreo4;
    private javax.swing.JLabel lblCorreo5;
    private javax.swing.JLabel lblCorreo6;
    private javax.swing.JLabel lblCorreo7;
    private javax.swing.JLabel lblCorreo8;
    private javax.swing.JLabel lblCorreo9;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEditar1;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblImagenID2;
    private javax.swing.JLabel lblImagenID3;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JSpinner spnNumHuesped;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumIdentidad;
    private javax.swing.JTextField txtNumTelefono;
    private javax.swing.JTextField txtPrecioEstadia;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    // End of variables declaration//GEN-END:variables
}
