/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Usuario;
import javax.swing.JOptionPane;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class GuiUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new foArm IfrmRegistroUsuario
     */
    public GuiUsuario() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtPrimerNombre = new javax.swing.JTextField();
        lblCajaPrimerNombre = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lblCajaPrimerApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        lblCajaSegundoApellido = new javax.swing.JLabel();
        txtCorreoElecronico = new javax.swing.JTextField();
        lblCajaCorreoElectronico = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        lblCajaContrasenia = new javax.swing.JLabel();
        txtEncabezado = new javax.swing.JLabel();
        lblUsuarioImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        lblCajaSegundoNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblImagenConTransaparencia1 = new javax.swing.JLabel();
        lblImagenConTransaparencia = new javax.swing.JLabel();
        lblImagenConTransaparencia2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblFondoGradiante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));
        setClosable(true);
        setMaximumSize(new java.awt.Dimension(960, 550));
        setRequestFocusEnabled(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrimerNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtPrimerNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrimerNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtPrimerNombre.setText("Primer Nombre");
        txtPrimerNombre.setBorder(null);
        txtPrimerNombre.setOpaque(false);
        txtPrimerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerNombreMouseClicked(evt);
            }
        });
        txtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, 20));

        lblCajaPrimerNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 260, 40));

        txtPrimerApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtPrimerApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrimerApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtPrimerApellido.setText("Primer Apellido");
        txtPrimerApellido.setBorder(null);
        txtPrimerApellido.setOpaque(false);
        txtPrimerApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrimerApellidoMouseClicked(evt);
            }
        });
        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 20));

        lblCajaPrimerApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, 40));

        txtSegundoApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSegundoApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundoApellido.setText("Segundo Apellido");
        txtSegundoApellido.setBorder(null);
        txtSegundoApellido.setOpaque(false);
        txtSegundoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSegundoApellidoMouseClicked(evt);
            }
        });
        txtSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 20));

        lblCajaSegundoApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 260, 60));

        txtCorreoElecronico.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreoElecronico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCorreoElecronico.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreoElecronico.setText("Correo Electronico");
        txtCorreoElecronico.setBorder(null);
        txtCorreoElecronico.setOpaque(false);
        txtCorreoElecronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoElecronicoMouseClicked(evt);
            }
        });
        txtCorreoElecronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElecronicoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCorreoElecronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 230, 20));

        lblCajaCorreoElectronico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 260, 60));

        txtContrasenia.setBackground(new java.awt.Color(0, 0, 0));
        txtContrasenia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasenia.setText("Contraseña");
        txtContrasenia.setBorder(null);
        txtContrasenia.setOpaque(false);
        txtContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseniaMouseClicked(evt);
            }
        });
        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        jPanel2.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 230, 20));

        lblCajaContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 260, 60));

        txtEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setText("REGISTRAR USUARIO");
        jPanel2.add(txtEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        lblUsuarioImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario 128 x 128.png"))); // NOI18N
        jPanel2.add(lblUsuarioImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 140, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Contraseña.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 40));

        txtSegundoNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtSegundoNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSegundoNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundoNombre.setText("Segundo Nombre");
        txtSegundoNombre.setBorder(null);
        txtSegundoNombre.setOpaque(false);
        txtSegundoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSegundoNombreMouseClicked(evt);
            }
        });
        txtSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 20));

        lblCajaSegundoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formulario registro.png"))); // NOI18N
        jPanel2.add(lblCajaSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 80, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo usuario.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 80, 70));

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegistrarUsuario1.png"))); // NOI18N
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegistrarUsuario3.png"))); // NOI18N
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRegistrarUsuario2.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 80, 70));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar registro 1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar registro 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar registro 2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 130, 40));

        lblImagenConTransaparencia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel2.add(lblImagenConTransaparencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        lblImagenConTransaparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel2.add(lblImagenConTransaparencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        lblImagenConTransaparencia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo con transparencia.png"))); // NOI18N
        jPanel2.add(lblImagenConTransaparencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 480));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 380, 480));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1455555016_users-15_icon-icons.com_53267.png"))); // NOI18N
        jLabel12.setText("jLabel11");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 80, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 90, 80));

        btnInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar secion 3.png"))); // NOI18N
        btnInicioSesion.setBorder(null);
        btnInicioSesion.setBorderPainted(false);
        btnInicioSesion.setContentAreaFilled(false);
        btnInicioSesion.setFocusPainted(false);
        btnInicioSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar secion 2.png"))); // NOI18N
        btnInicioSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar secion 1.png"))); // NOI18N
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 200, 40));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("¿Ya estas registrado?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 230, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAzulTransaparente.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 380, 240));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAzulTransaparente.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 380, 240));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAzulTransaparente.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 380, 240));

        lblFondoGradiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Blue Modern City Vector Illustration.png"))); // NOI18N
        jPanel1.add(lblFondoGradiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 990, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed

    private void txtSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNombreActionPerformed

    private void txtPrimerNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerNombreMouseClicked
        // TODO add your handling code here:
        this.txtPrimerNombre.setText("");

    }//GEN-LAST:event_txtPrimerNombreMouseClicked

    private void txtSegundoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSegundoNombreMouseClicked
        this.txtSegundoNombre.setText("");
    }//GEN-LAST:event_txtSegundoNombreMouseClicked

    private void txtPrimerApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrimerApellidoMouseClicked
        this.txtPrimerApellido.setText("");
    }//GEN-LAST:event_txtPrimerApellidoMouseClicked

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtSegundoApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSegundoApellidoMouseClicked
        // TODO add your handling code here:
        this.txtSegundoApellido.setText("");

    }//GEN-LAST:event_txtSegundoApellidoMouseClicked

    private void txtSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoActionPerformed

    private void txtCorreoElecronicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoElecronicoMouseClicked
        // TODO add your handling code here:
        this.txtCorreoElecronico.setText("");
    }//GEN-LAST:event_txtCorreoElecronicoMouseClicked

    private void txtCorreoElecronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElecronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElecronicoActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void txtContraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseniaMouseClicked
        // TODO add your handling code here:
        this.txtContrasenia.setText("");
    }//GEN-LAST:event_txtContraseniaMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            //Obtener el valor de los textBox
            String pNombre, sNombre, pApellido, sApellido, correo, contrasenia;
            pNombre = this.txtPrimerNombre.getText();
            sNombre = this.txtSegundoNombre.getText();
            pApellido = this.txtPrimerApellido.getText();
            sApellido = this.txtSegundoApellido.getText();
            correo = this.txtCorreoElecronico.getText();
            contrasenia = this.txtContrasenia.getText();
            //Crear el objeto Usuario
            Usuario us = new Usuario();
            us.setpNombre(pNombre);
            us.setsNombre(sNombre);
            us.setpApellido(pApellido);
            us.setsApellido(sApellido);
            us.setEmail(correo);
            us.setContrasenia(contrasenia);
            //3. Agregarlo a la gestion
            PantallaPrincipal.gUsuario.agregarUSuario(us);
            AdminSerializacion.guardar(PantallaPrincipal.gUsuario, "Usuario.obj");

            JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");

            this.txtPrimerNombre.setText("Primer nombre");
            this.txtSegundoNombre.setText("Segundo nombre");
            this.txtPrimerApellido.setText("Primer apellido");
            this.txtSegundoApellido.setText("Segundo apellido");
            this.txtCorreoElecronico.setText("Correo electronico");
            this.txtContrasenia.setText("Contraseña");

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        GuiLogin login = new GuiLogin();
        PantallaPrincipal.panelEscritorio.add(login);
        dispose();
        login.setVisible(true);

    }//GEN-LAST:event_btnInicioSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCajaContrasenia;
    private javax.swing.JLabel lblCajaCorreoElectronico;
    private javax.swing.JLabel lblCajaPrimerApellido;
    private javax.swing.JLabel lblCajaPrimerNombre;
    private javax.swing.JLabel lblCajaSegundoApellido;
    private javax.swing.JLabel lblCajaSegundoNombre;
    private javax.swing.JLabel lblFondoGradiante;
    private javax.swing.JLabel lblImagenConTransaparencia;
    private javax.swing.JLabel lblImagenConTransaparencia1;
    private javax.swing.JLabel lblImagenConTransaparencia2;
    private javax.swing.JLabel lblUsuarioImagen;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreoElecronico;
    private javax.swing.JLabel txtEncabezado;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
