/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Caja;
import gestiones.*;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import utilitario.AdminSerializacion;

/**
 *
 * @author aarve
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    public static GestionAreaDeTrabajo gArea = new GestionAreaDeTrabajo();
    public static GestionCategoriaHabitacion gCatHab = new GestionCategoriaHabitacion();
    public static GestionUsuario gUsuario = new GestionUsuario();
    public static GestionEmpleado gEmpleado = new GestionEmpleado();
    public static GestionHotel gHtl = new GestionHotel();
    public static GestionHabitacion gHab = new GestionHabitacion();
    public static GestionReserva gRsv = new GestionReserva();
    public static GestionProveedor gProv = new GestionProveedor();
    public static GestionProducto gProd = new GestionProducto();
    public static GestionCaja gCaja = new GestionCaja();
    public static GestionFactura gFact = new GestionFactura();

    public static GestionListaProductos gLstProductos = new GestionListaProductos();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        super.setTitle("Sistema Hotel");
        try {

            gArea = (GestionAreaDeTrabajo) AdminSerializacion.obtener("AreaDeTrabajo.obj");
            gCatHab = (GestionCategoriaHabitacion) AdminSerializacion.obtener("gCatHab.obj");
            gUsuario = (GestionUsuario) AdminSerializacion.obtener("Usuario.obj");
            gEmpleado = (GestionEmpleado) AdminSerializacion.obtener("objEmpleado.obj");
            gHtl = (GestionHotel) AdminSerializacion.obtener("objHotel.obj");
            gHab = (GestionHabitacion) AdminSerializacion.obtener("objHabitacion.obj");
            gRsv = (GestionReserva) AdminSerializacion.obtener("objReserva.obj");
            gProv = (GestionProveedor) AdminSerializacion.obtener("objProveedor.obj");
            gProd = (GestionProducto) AdminSerializacion.obtener("objProductos.obj");
            // gCaja = (GestionCaja) AdminSerializacion.obtener("objCaja.obj");
            // gFact = (GestionFactura) AdminSerializacion.obtener("objFactura.obj");

        } catch (Exception e) {
        }

        initComponents();

        this.MenuHotel.setEnabled(false);
        this.MenuEmpleado.setEnabled(false);
        this.MenuHospedaje.setEnabled(false);
        this.MenuProductos.setEnabled(false);
        this.mnuPago.setEnabled(false);
        this.menuCerrarSesion.setEnabled(false);

        super.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuHotel = new javax.swing.JMenu();
        mnuCatHabitacion = new javax.swing.JMenuItem();
        mnuHabitacion = new javax.swing.JMenuItem();
        btnHotel = new javax.swing.JMenuItem();
        MenuEmpleado = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        mnuAreasTrabajo = new javax.swing.JMenuItem();
        MenuHospedaje = new javax.swing.JMenu();
        mnuHacerReserva = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenu();
        mnuProveedor = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuCarrito = new javax.swing.JMenuItem();
        mnuPago = new javax.swing.JMenu();
        mnuReservas1 = new javax.swing.JMenuItem();
        MenuSesion = new javax.swing.JMenu();
        mnuRegistroUsuario = new javax.swing.JMenuItem();
        menuInicioSesion = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        MenuHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1497618989-3_85123.png"))); // NOI18N
        MenuHotel.setMnemonic('e');
        MenuHotel.setText("Hotel");

        mnuCatHabitacion.setMnemonic('y');
        mnuCatHabitacion.setText("Categorias de habitacion");
        mnuCatHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatHabitacionActionPerformed(evt);
            }
        });
        MenuHotel.add(mnuCatHabitacion);

        mnuHabitacion.setMnemonic('p');
        mnuHabitacion.setText("Habitaciones");
        mnuHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHabitacionActionPerformed(evt);
            }
        });
        MenuHotel.add(mnuHabitacion);

        btnHotel.setMnemonic('d');
        btnHotel.setText("Descripcion del Hotel");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });
        MenuHotel.add(btnHotel);

        menuBar.add(MenuHotel);

        MenuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado.png"))); // NOI18N
        MenuEmpleado.setMnemonic('h');
        MenuEmpleado.setText("Empleados");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Empleados");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        MenuEmpleado.add(contentMenuItem);

        mnuAreasTrabajo.setMnemonic('t');
        mnuAreasTrabajo.setText("Areas de trabajo");
        mnuAreasTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAreasTrabajoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(mnuAreasTrabajo);

        menuBar.add(MenuEmpleado);

        MenuHospedaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/travel-holiday-vacation-327_89074.png"))); // NOI18N
        MenuHospedaje.setMnemonic('h');
        MenuHospedaje.setText("Hospedaje");

        mnuHacerReserva.setMnemonic('c');
        mnuHacerReserva.setText("Hacer reserva");
        mnuHacerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHacerReservaActionPerformed(evt);
            }
        });
        MenuHospedaje.add(mnuHacerReserva);

        menuBar.add(MenuHospedaje);

        MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hand-shopping-bag_46878.png"))); // NOI18N
        MenuProductos.setText("Tienda");

        mnuProveedor.setMnemonic('t');
        mnuProveedor.setText("Proveedor de productos");
        mnuProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedorActionPerformed(evt);
            }
        });
        MenuProductos.add(mnuProveedor);

        mnuProductos.setMnemonic('c');
        mnuProductos.setText("Productos disponibles");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        MenuProductos.add(mnuProductos);

        mnuCarrito.setMnemonic('c');
        mnuCarrito.setText("Venta de productos");
        mnuCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarritoActionPerformed(evt);
            }
        });
        MenuProductos.add(mnuCarrito);

        menuBar.add(MenuProductos);

        mnuPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        mnuPago.setMnemonic('h');
        mnuPago.setText("Pago reserva");

        mnuReservas1.setMnemonic('c');
        mnuReservas1.setText("Pago reserva");
        mnuReservas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReservas1ActionPerformed(evt);
            }
        });
        mnuPago.add(mnuReservas1);

        menuBar.add(mnuPago);

        MenuSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        MenuSesion.setMnemonic('h');
        MenuSesion.setText("Sesión");

        mnuRegistroUsuario.setMnemonic('c');
        mnuRegistroUsuario.setText("Registro de usuarios");
        mnuRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroUsuarioActionPerformed(evt);
            }
        });
        MenuSesion.add(mnuRegistroUsuario);

        menuInicioSesion.setMnemonic('a');
        menuInicioSesion.setText("Inicio de sesión");
        menuInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioSesionActionPerformed(evt);
            }
        });
        MenuSesion.add(menuInicioSesion);

        menuCerrarSesion.setMnemonic('a');
        menuCerrarSesion.setText("Cerrar sesión");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        MenuSesion.add(menuCerrarSesion);

        menuBar.add(MenuSesion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAreasTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAreasTrabajoActionPerformed
        // TODO add your handling code here:
        GuiAreasDeTrabajo guiAreas = new GuiAreasDeTrabajo();
        this.panelEscritorio.add(guiAreas);
        guiAreas.setVisible(true);
    }//GEN-LAST:event_mnuAreasTrabajoActionPerformed

    private void mnuCatHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatHabitacionActionPerformed
        // TODO add your handling code here:
        GuiCategoriaHabitacion guiCatHab = new GuiCategoriaHabitacion();
        panelEscritorio.add(guiCatHab);
        guiCatHab.setVisible(true);
    }//GEN-LAST:event_mnuCatHabitacionActionPerformed

    private void mnuRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroUsuarioActionPerformed
        // TODO add your handling code here:
        GuiUsuario guiUs = new GuiUsuario();
        panelEscritorio.add(guiUs);
        guiUs.setVisible(true);
    }//GEN-LAST:event_mnuRegistroUsuarioActionPerformed

    private void mnuHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHabitacionActionPerformed
        // TODO add your handling code here:
        GuiHabitacion gHabitacion = new GuiHabitacion();
        panelEscritorio.add(gHabitacion);
        gHabitacion.setVisible(true);
    }//GEN-LAST:event_mnuHabitacionActionPerformed

    private void menuInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioSesionActionPerformed
        // TODO add your handling code here:

        GuiLogin loging = new GuiLogin();

        Dimension jInternalFrameSize = loging.getSize();//Obtiene de las dimensiones del internalFrame
        Dimension desktopSize = this.getSize(); //Obtiene las dimensiones desktop 
        loging.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        panelEscritorio.add(loging);
        loging.setVisible(true);
    }//GEN-LAST:event_menuInicioSesionActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.MenuEmpleado.setEnabled(false);
            this.MenuHotel.setEnabled(false);
            this.menuCerrarSesion.setEnabled(false);
            this.menuInicioSesion.setEnabled(true);
            this.mnuRegistroUsuario.setEnabled(true);
            this.MenuHospedaje.setEnabled(false);
            this.MenuProductos.setEnabled(false);
            this.mnuPago.setEnabled(false);

        }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
        GuiEmpleados guiEmpleado = new GuiEmpleados();
        panelEscritorio.add(guiEmpleado);
        guiEmpleado.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        // TODO add your handling code here:
        GuiHotel htl = new GuiHotel();
        panelEscritorio.add(htl);
        htl.setVisible(true);
    }//GEN-LAST:event_btnHotelActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        // TODO add your handling code here:
        GuiProducto guiProducto = new GuiProducto();
        panelEscritorio.add(guiProducto);
        guiProducto.setVisible(true);
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedorActionPerformed
        // TODO add your handling code here:
        GuiProveedor guiProveedor = new GuiProveedor();
        panelEscritorio.add(guiProveedor);
        guiProveedor.setVisible(true);
    }//GEN-LAST:event_mnuProveedorActionPerformed

    private void mnuReservas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservas1ActionPerformed
        // TODO add your handling code here:

        GuiCajaReservas guiRsv = new GuiCajaReservas();
        panelEscritorio.add(guiRsv);
        guiRsv.setVisible(true);

    }//GEN-LAST:event_mnuReservas1ActionPerformed

    private void mnuCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarritoActionPerformed
        // TODO add your handling code here:
        // GuiListaCompras lista = new GuiListaCompras();
        // panelEscritorio.add(lista);
        // lista.setVisible(true);

        SeleccionarProductos guiSeleccionar = new SeleccionarProductos();
        panelEscritorio.add(guiSeleccionar);
        guiSeleccionar.setVisible(true);
    }//GEN-LAST:event_mnuCarritoActionPerformed

    private void mnuHacerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHacerReservaActionPerformed
        // TODO add your handling code here:
        GuiReserva guiRsv = new GuiReserva();
        panelEscritorio.add(guiRsv);
        guiRsv.setVisible(true);
    }//GEN-LAST:event_mnuHacerReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu MenuEmpleado;
    public static javax.swing.JMenu MenuHospedaje;
    public static javax.swing.JMenu MenuHotel;
    public static javax.swing.JMenu MenuProductos;
    private javax.swing.JMenu MenuSesion;
    private javax.swing.JMenuItem btnHotel;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuInicioSesion;
    private javax.swing.JMenuItem mnuAreasTrabajo;
    private javax.swing.JMenuItem mnuCarrito;
    private javax.swing.JMenuItem mnuCatHabitacion;
    private javax.swing.JMenuItem mnuHabitacion;
    private javax.swing.JMenuItem mnuHacerReserva;
    public static javax.swing.JMenu mnuPago;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuProveedor;
    private javax.swing.JMenuItem mnuRegistroUsuario;
    private javax.swing.JMenuItem mnuReservas1;
    public static javax.swing.JDesktopPane panelEscritorio;
    // End of variables declaration//GEN-END:variables

}
