/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.ListaProductos;
import clases.Producto;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aarve
 */
public class SeleccionarProductos extends javax.swing.JInternalFrame {

    private boolean agregando = false;
    private boolean codigo = false;
    private int posicionElemento;

    /**
     * Creates new form SeleccionarProductos
     */
    public SeleccionarProductos() {
        initComponents();
        PantallaPrincipal.gLstProductos.lstListaProductos.clear();
        this.txtCodigoProducto.setEnabled(false);
        this.cbxProducto.setEnabled(false);
        this.actualizarElementosEnTabla();
        this.cbxProducto.setModel(PantallaPrincipal.gProd.getComboboxModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCostoTotal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCaja = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        rbtnLista = new javax.swing.JRadioButton();
        rbtnCodigo = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaProductos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCostoTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblCostoTotal.setText("Costo total");
        jPanel1.add(lblCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 40, -1));

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Total");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 30, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nuevo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("Pasar a caja");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        btnCaja.setBorder(null);
        btnCaja.setBorderPainted(false);
        btnCaja.setContentAreaFilled(false);
        btnCaja.setFocusPainted(false);
        btnCaja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja3.png"))); // NOI18N
        btnCaja.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja2.png"))); // NOI18N
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCajaMousePressed(evt);
            }
        });
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 60, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 60, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setFocusPainted(false);
        btnNuevo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 3 nuevo.png"))); // NOI18N
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton 2 nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 60, 40));

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setFocusPainted(false);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 2.png"))); // NOI18N
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 60, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton cancelar 2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 60, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 1.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 3.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton eliminar 2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 60, 40));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 1.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setFocusPainted(false);
        btnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton editar 2.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 60, 40));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 1.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 3.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton agregar 2 png.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 60, 40));

        txtCodigoProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoProducto.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoProducto.setText("Codigo");
        txtCodigoProducto.setBorder(null);
        txtCodigoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoProductoMousePressed(evt);
            }
        });
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 145, 40, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        cbxProducto.setBackground(new java.awt.Color(204, 204, 204));
        cbxProducto.setForeground(new java.awt.Color(0, 0, 0));
        cbxProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxProductoMousePressed(evt);
            }
        });
        jPanel1.add(cbxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 160, -1));

        buttonGroup1.add(rbtnLista);
        rbtnLista.setText("Seleccionar de la lista");
        rbtnLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnListaMousePressed(evt);
            }
        });
        jPanel1.add(rbtnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        buttonGroup1.add(rbtnCodigo);
        rbtnCodigo.setText("Por codigo");
        rbtnCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnCodigoMousePressed(evt);
            }
        });
        jPanel1.add(rbtnCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Generar reporte");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 70, 20));
        jPanel1.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 70, 30));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cancelar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 50, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Eliminar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 40, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Editar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 30, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Agregar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra botones.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 450, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo transaparente.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 790, 340));

        tblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListaProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1060, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFormulario.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 450));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFormulario.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCajaMousePressed

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        // TODO add your handling code here:
        GuiCaja pantallaCaja = new GuiCaja();
        PantallaPrincipal.panelEscritorio.add(pantallaCaja);
        pantallaCaja.setVisible(true);

    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.agregando = true;
        this.btnCaja.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnReportes.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:

        String nombreArchivo = "Listas de productos";
        String contenido = PantallaPrincipal.gLstProductos.getInformacionGestion();
        String ruta = "Reportes\\" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }


    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        this.btnCaja.setEnabled(true);
        this.btnCancelar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(true);
        this.btnReportes.setEnabled(true);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Esta seguro?", "Eliminar elemento", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            PantallaPrincipal.gLstProductos.eliminar(this.posicionElemento);
            this.actualizarElementosEnTabla();
        }
        this.btnCaja.setEnabled(true);
        this.btnCancelar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(true);
        this.btnReportes.setEnabled(true);


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.agregando = false;
        this.btnCaja.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnReportes.setEnabled(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            int cantidad;
            Producto producto;

            int index;
            if (agregando) {

                if (codigo) {

                    index = PantallaPrincipal.gProd.buscarPorId(Integer.parseInt(txtCodigoProducto.getText()));

                    codigo = false;
                } else {
                    index = cbxProducto.getSelectedIndex();
                }
                cantidad = (int) this.spnCantidad.getValue();
                if (cantidad < 1) {
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad para el producto seleccionado");
                } else {
                    producto = PantallaPrincipal.gProd.getProducto(index);

                    ListaProductos objListaProductos = new ListaProductos();
                    objListaProductos.setCantidad(cantidad);
                    objListaProductos.setProducto(producto);

                    PantallaPrincipal.gLstProductos.agregarCarrito(objListaProductos);
                    this.actualizarElementosEnTabla();
                    agregando = false;

                }
            } else {
                if (codigo) {

                    index = PantallaPrincipal.gProd.buscarPorId(Integer.parseInt(txtCodigoProducto.getText()));

                    codigo = false;
                } else {
                    index = cbxProducto.getSelectedIndex();
                }
                cantidad = (int) this.spnCantidad.getValue();
                if (cantidad < 1) {
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad para el producto seleccionado");
                } else {
                    producto = PantallaPrincipal.gProd.getProducto(index);

                    ListaProductos objListaProductos = new ListaProductos();
                    objListaProductos.setCantidad(cantidad);
                    objListaProductos.setProducto(producto);

                    PantallaPrincipal.gLstProductos.modificar(objListaProductos, posicionElemento);
                    this.actualizarElementosEnTabla();

                }

            }
            this.btnCaja.setEnabled(true);
            this.btnCancelar.setEnabled(false);
            this.btnEditar.setEnabled(false);
            this.btnEliminar.setEnabled(false);
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnReportes.setEnabled(true);
            this.cbxProducto.setEnabled(false);

            this.txtCodigoProducto.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar o editar" + e);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCodigoProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProductoMousePressed
        // TODO add your handling code here:
        this.txtCodigoProducto.setText("");
    }//GEN-LAST:event_txtCodigoProductoMousePressed

    private void cbxProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxProductoMousePressed

    }//GEN-LAST:event_cbxProductoMousePressed

    private void rbtnListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnListaMousePressed
        // TODO add your handling code here:
        this.codigo = false;
        this.txtCodigoProducto.setEnabled(false);
        this.cbxProducto.setEnabled(true);

    }//GEN-LAST:event_rbtnListaMousePressed

    private void rbtnCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCodigoMousePressed
        // TODO add your handling code here:
        codigo = true;
        this.txtCodigoProducto.setEnabled(true);
        this.cbxProducto.setEnabled(false);

    }//GEN-LAST:event_rbtnCodigoMousePressed

    private void tblListaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaProductosMousePressed
        // TODO add your handling code here:
        this.posicionElemento = tblListaProductos.getSelectedRow();
        ListaProductos objLista = new ListaProductos();
        objLista = PantallaPrincipal.gLstProductos.getObjeto(posicionElemento);
        int idProducto = objLista.getProducto().getIdProducto();
        int posicionProducto = PantallaPrincipal.gProd.buscarPorId(idProducto);
        this.cbxProducto.setSelectedIndex(posicionProducto);
        this.txtCodigoProducto.setText(Integer.toString(idProducto));
        this.spnCantidad.setValue(objLista.getCantidad());

        this.btnCaja.setEnabled(false);
        this.btnCancelar.setEnabled(true);
        this.btnEditar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(false);
        this.btnReportes.setEnabled(false);


    }//GEN-LAST:event_tblListaProductosMousePressed

    //Metodo para actualizar los elementos de la tabla
    public void actualizarElementosEnTabla() {

        String[] tituloColumnas = {"ID producto", "Nombre del producto", "Cantidad", "Costo unitario", "Costo total"};
        DefaultTableModel tablaListaProductos = new DefaultTableModel(PantallaPrincipal.gLstProductos.getArrayGestion(), tituloColumnas);

        this.tblListaProductos.setModel(tablaListaProductos);

        this.lblCostoTotal.setText(Double.toString(PantallaPrincipal.gLstProductos.total()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReportes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JRadioButton rbtnCodigo;
    private javax.swing.JRadioButton rbtnLista;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblListaProductos;
    private javax.swing.JTextField txtCodigoProducto;
    // End of variables declaration//GEN-END:variables
}
